3scale/3scale-operator

- Gopkg.lock
- Gopkg.toml
- Makefile
- README.md
This PR:
* Fixes some minor operator-sdk v0.2.1 direct dependency. operator-sdk in master was already v0.2.1 in master but not all direct operator-sdk dependencies matched what the "operator-sdk print-deps --as-file" generated
* Removes unnecessary imports from Gopkg.toml
* Fixes openshift/api version in Gopkg.toml to the revision commit that currently matches the v3.11 branch (no tag exists in the openshift/api repository)
* Regenerates Gopkg.toml
* Updates Makefile to use a locally installed operator-sdk command instead of a vendored one. This has been done because it is not supported by operator-sdk (see https://github.com/operator-framework/operator-sdk/issues/852). This breaks our current CI/CD integration and in a future PR will be fixed
* Updates README.md with an explanation of …
> Change operator dependencies

- .circleci/config.yml
- pkg/3scale/amp/Makefile
This PR adds a run step to the CircleCI 'build' job that installs operator-sdk v0.2.1 tag locally, which is the n used to be able to use the operator-sdk command.
It also updates all CircleCI Docker images that use Go to 1.11.
This PR is based on the contents of the branch that has been requested to be merged into master in the https://github.com/3scale/3scale-operator/pull/14 PR.
> Local operator sdk command on ci

- build/Dockerfile
- cmd/manager/main.go
- deploy/operator.yaml
- deploy/role.yaml
Some files change when a new operator project is created in
v0.2.1 compared to previous versions (a notable change
is the change of logging methods). This commit updates
our existing files to match what is created in v0.2.1 for
non api/controlled related files.
> Upgrade contents of files that change from the upgrade to v0.2.1

- pkg/3scale/amp/component/apicast.go
- pkg/3scale/amp/component/backend.go
- pkg/3scale/amp/component/highavailability.go
- pkg/3scale/amp/component/memcached.go
- pkg/3scale/amp/component/mysql.go
- pkg/3scale/amp/component/productized.go
- pkg/3scale/amp/component/redis.go
- pkg/3scale/amp/component/s3.go
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/wildcardrouter.go
- pkg/3scale/amp/component/zync.go
Refactor generator component options into required and nonrequired
Refactor options for apicast, backend, ha, memcached,
mysql, productized, redis, s3, system and wildcardrouter
components.
This has been done because at operator level you need to be able to set the secrets fields when constructing the components, to be able to reconcile the possible secrets that already exist.
> Refactor component options

- pkg/3scale/amp/component/apicast.go
- pkg/3scale/amp/component/backend.go
- pkg/3scale/amp/component/s3.go
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/zync.go
Refactor secret names and field names into constants
for apicast, backend, s3, system and zync components
> Move secret field names and names into constants

- .circleci/config.yml
In case the templates cannot be generated or are out-of-date it's best
to directly not execute the deployment of the api management platform.
> Make 'deploy' CircleCI job dependant on 'generator' job in 'templates' workflow

- .circleci/config.yml
- build/Dockerfile
- deploy/operator.orig
- deploy/role.yaml
This PR adds a new job that deploys the 3scale-operator and an ApiManager installation (the 3scale standard product). It also includes some refactorings on the CircleCI file and updates some needed permissions for the operator to work with the deployed ServiceAccount (and not being admin)
> Add installation basic int tests

- pkg/3scale/amp/component/productized.go
- pkg/3scale/amp/operator/productized.go
The same memcached image is used in both development and productized versions. There is no need to have productized-specific modifications for it.
> installation: Use the same memcached image for productized/devel version

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml
- pkg/3scale/amp/component/amphatemplate.go
- pkg/3scale/amp/component/highavailability.go
- pkg/3scale/amp/component/mysql.go
- pkg/3scale/amp/component/system.go
The system-mysql service has been moved into the
mysql component. This has been done because there are situations
where we don't want to deploy a mysql pod and instead use another
element, like an external database or a different database type.
By moving the system-mysql specific elements into the mysql component
we make sure that when this component is not used then this
elements are no created, and also we don't need another element
to remove them.
Also, highavailability component has been updated to create the secret
by itself because when highavailabilty compoent is used no mysql
component is used in the cluster.
> Move system-mysql service into mysql component in 3scale datamodel

- deploy/crds/api_v1alpha1_tenant_crd.yaml
- pkg/controller/tenant/internal_reconciler.go
- pkg/controller/tenant/tenant_controller.go
Fixes #51 
Tenant controller will try to read master secret and admin password secret only from tenant CR namespace. Namespace cannot be specified in spec.
> tenant controller: read secrets from CR namespace only

- doc/reference.md
Adds more reference documentation for APIManager spec and secrets.
cc @hallelujah , @guicassolato can you review the field description of Porta fields and also provide some description information for the ones that have a TODO?
> Add more fields into the APIManager Spec documentation

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/operator/system.go
Make the provider admin mail configurable when a
deploy is performed via a parameter
named ADMIN_EMAIL, and the USER_EMAIL system envvar
is set from that value.
> Add provider mail param

- test/e2e/apimanager_controller_test.go
- test/e2e/full_test.go
Increases Cleanup timeout to try to solve cleanup problems between tests.
Also adds some elapsed time logging in some parts of the tests
> Improve tests stability

- .circleci/config.yml
Sometimes the 10m with no output default limit was reached when deploying 3scale template which is too little sometimes. This PR increases it.
> Increase no_output_timeout in 3scale template deployment

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml
- pkg/3scale/amp/component/ampimages.go
- pkg/3scale/amp/component/apicast.go
- pkg/3scale/amp/component/backend.go
- pkg/3scale/amp/component/buildconfigs.go
- pkg/3scale/amp/component/highavailability.go
- pkg/3scale/amp/component/memcached.go
- pkg/3scale/amp/component/mysql.go
- pkg/3scale/amp/component/redis.go
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/wildcardrouter.go
- pkg/3scale/amp/component/zync.go
This comes from the issue https://github.com/3scale/3scale-operator/issues/31.
This change renames the 3scale.component and 3scale.component-element labels to threescale_component and threescale_component_element labels to be compatible with Prometheus labels datamodel.
Adding this would make those labels compatible with prometheus. However, as you can see in the following Kubernetes link https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set , some automated Kubernetes elements/controllers add labels that use / as some part of the label, which is incompatible with the Prometheus data model. Our operator (which has controllers )also  might need (and probably will) to add labels to perform object management.
So in my opinion what really solves …
> Relabel 3scale elements

- pkg/controller/binding/binding_controller.go
- pkg/controller/consolidated/consolidated_controller.go
- test/e2e/manifests/apis.yml
Due to changes in the latest operator-sdk, the status subresource was not working, this PR fixes by using the specific status client.
> Consolidated status subresource 

- deploy/crds/apps_v1alpha1_apimanager_cr_s3.yaml
- deploy/crds/apps_v1alpha1_apimanager_crd.yaml
- doc/apimanager-reference.md
- pkg/apis/apps/v1alpha1/apimanager_types.go
Due to the fact that the openapi generator does not correctly generate OpenAPI validation when the json field contains a number (see https://github.com/operator-framework/operator-sdk/issues/1120), the field was renamed to 'sthree', but I'm not totally convinced of that name.
This PR renames the json field to 'amazonSimpleStorageService'. Do you think this is a better/good name for this field?
I did not choose 'simpleStorageService' because I'd like to make explicit that it's an amazon service. S3 is clear enough that is an amazon service but 'simpleStorageService' seems lot more generic so that's why I added the amazon prefix.
What do you think?
> APIManager - rename sthree json field to amazonSimpleStorageService

- doc/apimanager-reference.md
- pkg/3scale/amp/product/images.go
- pkg/3scale/amp/product/release_2_5.go
This PR adds a new ProductVersion for the 3scale API Management 2.5 release in the Operator productVersion field.
The possible update to PostgreSQL 10 will be added in another PR and the change in the templates too
> Create ProductVersion 2.5 for the Operator

- pkg/3scale/amp/component/mysql.go
- pkg/3scale/amp/component/zync.go
This PR removes unneeded NodePort fields in some services because the zero-value of NodePort is already 0 so there's no need to specify it.
> Remove unneeded NodePort and let use the zero-value in components

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml
- pkg/3scale/amp/cmd/template.go
- pkg/3scale/amp/component/ampimages.go
- pkg/3scale/amp/component/zync.go
- pkg/3scale/amp/product/release_2_5.go
- pkg/3scale/amp/product/upstream.go
This PR upgrades the PostgreSQL present in operator/templates used by Zync from 9.5 to 10. The changes are:
*  Remove ImageStreamTag "9.5" of the 'postgresql' ImageStream and replace it with a ImageStreamTag with the name "10". The tag name has the following image associated, using the 'latest' tag: registry.access.redhat.com/rhscl/postgresql-10-rhel7
* Replace the ImageChange trigger in the 'zync-database' from postgresql:9 to postgresql:10 in order to use the new ImageStreamTag "10". This is done so the 'zync-database' DeploymentConfig gets the new tag name
* Update the 'upstream' productVersion in the operator to use the new PostgreSQL 10 image (registry.access.redhat.com/rhscl/postgresql-10-rhel7), and also the '2.5' productVersion to use that new image too
> Upgrade to postgresql10

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml
- pkg/3scale/amp/cmd/template.go
- pkg/3scale/amp/component/productized.go
- pkg/3scale/amp/manual-templates/amp/apicast.yml
- pkg/3scale/amp/manual-templates/productized-templates/apicast-gateway/apicast.yml
This PR upgrades the templates contents to use AMP 2.5.0 preparing it for the upcoming changes.
This assumes correct image URLs, although changes might be needed if was not the case.
> Upgrade template images to 2.5

- pkg/apis/capabilities/v1alpha1/api_types.go
fixes https://github.com/3scale/3scale-operator/issues/98
> Uses ProductionPublicBaseURL field instead of incorrect PrivateBaseURL

- pkg/apis/capabilities/v1alpha1/limit_types.go
- pkg/apis/capabilities/v1alpha1/mappingrule_types.go
- pkg/controller/binding/binding_controller.go
- test/e2e/full_test.go
* Improve tests by making sure the state is in sync.
* The lastSync field now it's only updated/added when the state is in sync.
* Fixed an issue with detecting the default "Hits" metric in porta.
> Add state comparison to validate tests

- doc/apimanager-reference.md
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml
- pkg/3scale/amp/component/apicast.go
- pkg/3scale/amp/component/apicast_options_builder.go
- pkg/3scale/amp/component/highavailability.go
- pkg/3scale/amp/component/highavailability_options_builder.go
- pkg/3scale/amp/operator/apicast.go
- pkg/3scale/amp/operator/highavailability.go
This PR removes the apicast-redis secret, that contained redis URLs for apicast production and apicast staging.
The removal is done both in the operator and in the templates.
It also removes the environment variables created in the apicast-staging and apicast-production DeploymentConfigs that referenced the apicast-redis secret fields respectively
> Remove apicast redis secret

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml
- pkg/3scale/amp/cmd/template.go
- pkg/3scale/amp/component/ampimages.go
- pkg/3scale/amp/component/ampimages_options_builder.go
- pkg/3scale/amp/component/highavailability.go
- pkg/3scale/amp/component/memcached.go
- pkg/3scale/amp/component/memcached_options_builder.go
- pkg/3scale/amp/component/mysql.go
- pkg/3scale/amp/component/mysql_options_builder.go
- pkg/3scale/amp/component/redis.go
- pkg/3scale/amp/component/redis_options_builder.go
- pkg/3scale/amp/component/zync.go
- pkg/3scale/amp/operator/ampimages.go
- pkg/3scale/amp/operator/memcached.go
- pkg/3scale/amp/operator/mysql.go
- pkg/3scale/amp/operator/redis.go
This PR makes the following DeploymentConfig elements use ImageStreams:
* backend-redis
* system-redis
* system-mysql
* system-memcache
This makes all DeploymentConfigs of the platform use ImageStreams so we have a more homogeneous way of handling the image changes and has the following advantages:
* Allow easier updates of the Images (with import-image command)
* All elements of our platform would use the same method to obtain the images. This should simplify tasks like management of them and the 3scale-operator source code
* It will be easier to start the steps of probably finally remove ImageStreams in a future step so the platform is compatible with Kubernetes (instead of starting with different scenarios and situations), so I think is a good first step to prepare for that if the need …
> Migrate dbs to imagestreams

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml
- pkg/3scale/amp/component/ampimages.go
- pkg/3scale/amp/component/productized.go
PR to prepare for the use of registry.redhat.io in the images for 2.6 releases and newer ones.
The old RedHat registry access.redhat.com will be deprecated and newer images are not going to be published on it. New images are going to be published in registry.redhat.io. This registry requires authentication.
This PR allows configuring the authentication credentials for the registry.redhat.io via a secret called 'threescale-registry-auth'. This secret is associated to the "amp" ServiceAccount that has been assigned to all the DeploymentConfig elements of the platform.
The final user is the only one that knows the credentials it has so the secret must be created by them with the specific fields needed and values needed before deploying the APIManager/the templates. Otherwise, the deploy will …
> Prepare usage of registry.redhat.io registry

- doc/apimanager-reference.md
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml
- pkg/3scale/amp/component/highavailability.go
- pkg/3scale/amp/component/highavailability_options_builder.go
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/system_options_builder.go
- pkg/3scale/amp/operator/highavailability.go
- pkg/3scale/amp/operator/system.go
This PR:
* Adds the SYSTEM_REDIS_URL parameter to all templates and not only to the HA one. Additionally Makes this parameter required without a default value only in the HA template.
* Adds the SYSTEM_MESSAGE_BUS_REDIS_URL parameter to all templates. Additionally Makes this parameter required without a default value only in the HA template.
* Sets the MESSAGE_BUS_URL attribute in the 'system-redis' secret gathering its value from the SYSTEM_MESSAGE_BUS_REDIS_URL in the case of templates. In the case of the operator it's also automatically generated if not specified
* system's redis url is 'redis://system-redis:6379/1' by default (as before)
* system's message bus redis url is 'redis://system-redis:6379/8' by default (as before)
*  Adds the environment variable MESSAGE_BUS_REDIS_URL in …
> Configurable system redis urls

- pkg/3scale/amp/component/ampimages.go
- pkg/3scale/amp/component/apicast.go
- pkg/3scale/amp/component/backend.go
- pkg/3scale/amp/component/buildconfigs.go
- pkg/3scale/amp/component/evaluation.go
- pkg/3scale/amp/component/highavailability.go
- pkg/3scale/amp/component/memcached.go
- pkg/3scale/amp/component/mysql.go
- pkg/3scale/amp/component/productized.go
- pkg/3scale/amp/component/redis.go
- pkg/3scale/amp/component/s3.go
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/system_mysql_image.go
- pkg/3scale/amp/component/system_postgresql.go
- pkg/3scale/amp/component/system_postgresql_image.go
- pkg/3scale/amp/component/wildcardrouter.go
- pkg/3scale/amp/component/zync.go
- pkg/apis/common/kubernetes_types.go
- pkg/controller/apimanager/apimanager_controller.go
- pkg/helper/helper.go
Avoid the use of RawExtension and unnecessary conversions of objects, other than for templates
Signed-off-by: Babak Mozaffari <bmozaffa@redhat.com>
> Avoid frequent RawExtension conversions

- .circleci/config.yml
This PR fixes the image build step in the nightly CircleCI task was being marked as correct when build images were failing.
> Check for image build exit status in CircleCI

- pkg/3scale/amp/manual-templates/amp/build.yml
zync uses Docker build now (https://github.com/3scale/zync/pull/197)
/cc @3scale/qe
> [build] update zync build

- deploy/crds/apps_v1alpha1_apimanager_crd.yaml
- doc/apimanager-reference.md
- doc/user-guide.md
- pkg/3scale/amp/component/productized.go
- pkg/3scale/amp/operator/ampimages.go
- pkg/3scale/amp/operator/productized.go
- pkg/3scale/amp/operator/system.go
- pkg/3scale/amp/operator/system_mysql_image.go
- pkg/3scale/amp/operator/system_postgresql_image.go
- pkg/3scale/amp/product/images.go
- pkg/apis/apps/v1alpha1/apimanager_types.go
- pkg/apis/apps/v1alpha1/zz_generated.openapi.go
- pkg/controller/apimanager/apimanager_controller.go
- test/e2e/apimanager_controller_test.go
- test/e2e/full_test.go
This commit removes the ability to configure the productVersion
through the APIManager CR field.
The idea is that every new release of 3scale (excluding bugfix ones)
we'll provide a new operator version. In that regard this is the same
behaviour than before. When we were to release a new 3scale version
new code was needed to be added for the new URLs so this does not change
previous behaviour in that sense.
We'll stop providing upstream nightly configurability. Instead, we'll
provide an example CR deployment with the set of nightly images(by overriding
the image fields) in case someone needs it and we won't commit to support
that at all because of the inherently unstability of those images
and the purpose of them.
We'll probably also have an upstream version of the operator but in another …
> Remove operator-specific productVersion configurability

- deploy/crds/apps_v1alpha1_apimanager_cr_s3.yaml
- deploy/crds/apps_v1alpha1_apimanager_crd.yaml
- doc/apimanager-reference.md
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/component/s3.go
- pkg/3scale/amp/component/s3_options_builder.go
- pkg/3scale/amp/operator/s3.go
- pkg/apis/apps/v1alpha1/apimanager_types.go
When in the S3 context (both in templates and operator), the only value that makes sense to have is "s3" as the FILE_UPLOAD_STORAGE environment variable needed by system so we remove the configurability of it.
Part of the PR was already implemented by @matskiv in the https://github.com/3scale/3scale-operator/pull/147 but when a forked branch is created and then a PR submitted CircleCI tests are not currently working due to some credentials permissions/data. We will fix this as soon as we can and apply this solution now.
I merged the commit submitted by @matskiv in the other PR maintaining the original commit and author and I've submitted new commits that contain the parts that were still pending to be implemented.
> Remove configurable fileuploadstorage in operator and templates

- Makefile
- deploy/operator.yaml
- deploy/role.yaml
Operators created through operator-sdk by default expose Prometheus metrics through a Service that is created when deploying it (not 3scale but the operator itself).
The operator wasn't able to create the Service that is created for exposing the operator Prometheus metrics. That was because you cannot have a Service starting with a number (an error was shown). In the logs it could be seen:
```
{"level":"info","ts":1559141154.4200816,"logger":"cmd","msg":"failed to create or get service for metrics: Service \"3scale-operator\" is invalid: metadata.name: Invalid value: \"3scale-operator\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for …
```
> Fix operator not being able to create service for Prometheus metrics

- go.mod
- go.sum
- test/crds/crd_validation_test.go
Updated to newer version of operator-utils with float32 type support
Plan CRD test uncommented / added back
Signed-off-by: Babak Mozaffari <bmozaffa@redhat.com>
> Support for float32 / Plan crd unit testing

- deploy/role.yaml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml
- pkg/3scale/amp/component/zync.go
routes/status and routes/custom-host subresource do not have the same verbs than routes.
Applying them caused errors when deploying 3scale with non-privileged users.
This PR modifies the role permissions to specific verbs for routes/status (get verb only)
The same happened with routes/custom-host and has been changed too. routes/custom-host has been left with only the 'create' permission as originally requested.
> Fix zync que role permissions

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml
- pkg/3scale/amp/component/ampimages.go
- pkg/3scale/amp/component/ampimages_options_builder.go
- pkg/3scale/amp/component/zync.go
- pkg/3scale/amp/operator/ampimages.go
With the introduction of the PostgreSQL database to be used by System, we created a new ImageStream named system-postgresql. We did not reuse the 'postgresql' ImageStream because we want to manage triggered updates on the ImageStream independently.
Now the situation when deploying 3scale with system using postgresql would leave us with two imagestreams:
"postgresql"
"system-postgresql"
This PR changes that and renames the "postgresql" ImageStream to "zync-database-postgresql"
So we'll have two imagestreams:
"zync-database-postgresql"
"system-postgresql"
That will be able to be managed independently
> Rename postgresql imagestream

- pkg/apis/apps/v1alpha1/apimanager_types.go
- pkg/controller/apimanager/apimanager_controller.go
This PR applies some fixes and improvements derivated from the review that @bmozaffa performed on the APIManager reconciliation code. Those fixes are:
* Fixing SetDefaults APIManage method to correctly keep track of the changes detection
* Retrying reconciliation when Defaults initialization fails for some reason
* Updating some logs to better describe the actions happening
Thank you @bmozaffa
> Minor APIManager fixes

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml
- pkg/3scale/amp/cmd/template.go
- pkg/3scale/amp/component/ampimages.go
- pkg/3scale/amp/component/memcached.go
- pkg/3scale/amp/component/redis.go
- pkg/3scale/amp/component/system_mysql_image.go
- pkg/3scale/amp/component/system_postgresql_image.go
- pkg/3scale/amp/manual-templates/amp/apicast.yml
- pkg/3scale/amp/product/images.go
- pkg/3scale/amp/product/release_2_6.go
Changes:
* Updated AMP images to community based images with `3scale-2.6.0-ER1` tag
* Bumped AMP Release to 2.6
* Updated Database images to community based `centos` images
* Updated Memcached image to dockerhub image
* Patch memcached `readiness probe` to support replaced image
* Re-generated templates
> Community images 2.6

- .circleci/config.yml
Build nightly images only in the nightly task.
Templates workflow deploys nightly images, but does not build them.
Operator workflow deploys nightly images, but does not build them.
Avoid building `master` branch 3scale components on each PR of this repo. If any component build would fail, PR's on this repo would all be blocked and that is not acceptable. 
`master` branch 3scale components are all build nightly and PR's always use last night builds.  If any component build would fail, nightly task would fail and PR's of this repo would use latest successful master builds.
That is the tradeoff.
> templates workflow does not build nightly images on each PR

- pkg/3scale/amp/cmd/template.go
- pkg/3scale/amp/template/adapters/apicast.go
- pkg/3scale/amp/template/adapters/backend.go
- pkg/3scale/amp/template/adapters/eval.go
- pkg/3scale/amp/template/adapters/ha.go
- pkg/3scale/amp/template/adapters/images.go
- pkg/3scale/amp/template/adapters/memcached.go
- pkg/3scale/amp/template/adapters/redis.go
- pkg/3scale/amp/template/adapters/s3.go
- pkg/3scale/amp/template/adapters/system-mysql-image.go
- pkg/3scale/amp/template/adapters/system-mysql.go
- pkg/3scale/amp/template/adapters/system-postgresql-image.go
- pkg/3scale/amp/template/adapters/system-postgresql.go
- pkg/3scale/amp/template/adapters/system.go
- pkg/3scale/amp/template/adapters/zync.go
- pkg/3scale/amp/template/amp.go
- pkg/3scale/amp/template/ampeval.go
- pkg/3scale/amp/template/ampevals3.go
- pkg/3scale/amp/template/ampha.go
- pkg/3scale/amp/template/amppostgresql.go
- pkg/3scale/amp/template/amps3.go
- pkg/3scale/amp/template/factory.go
This PR backports the https://github.com/3scale/3scale-operator/pull/173 PR that refactors template generation factories that we want to include for 2.6 CR1
> [3] 2.6 stable backport template factory refactor

- deploy/role.yaml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/zync.go
This commits adds the route/custom-host update verb into the zync-que-role that is needed by the Zync component that has been requested by Zync team.
This change has a big impact where you need a privileged user to deploy 3scale from this point on.
This change should be temporary until we find a different way in Zync to do the desired tasks for CR1, but we add it so we can proceed with our internal testings for the moment.
https://issues.jboss.org/browse/THREESCALE-2939
> 2.6 stable prod add update routecustomhost [THREESCALE-2939]

- pkg/3scale/amp/manual-templates/amp/apicast.yml
This PR:
* Updates apicast template image to nightly
* Removes unused quay-auth imagepullsecret(now it gathers the image from a public quay registry)
> Update apicast template26

- pkg/3scale/amp/manual-templates/amp/apicast.yml
This PR:
* Updates apicast template image to use the existing quay community image
* Removes unused quay-auth imagepullsecret(now it gathers the image from a public quay registry)
> 2.6 stable updateapicast template26

- deploy/role.yaml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/zync.go
This PR reverts the addition of role permissions temporarily needed that were requiring admin privileges to be able to deploy the role that used them.
cc @mikz please approve this when the changes related to not needing this additional permission are in zync's master
Thank you.
> Revert pull request #187

- pkg/3scale/amp/component/system.go
2.6 stable backport system's fileStorage StorageClassName attribute not being set on operator
> 2.6-stable backport operator storageclassname fix

- pkg/3scale/amp/component/system.go
2.6 stable prod backport system's fileStorage StorageClassName attribute not being set on operator
> 2.6-stable-prod backport operator storageclassname fix

- pkg/3scale/amp/operator/backend.go
`REDIS_QUEUES_SENTINEL_HOSTS` was read from `backend-redis` secret, but not set in options object correctly. 
Secret reconciliation made both `REDIS_QUEUES_SENTINEL_HOSTS` and `REDIS_STORAGE_SENTINEL_HOSTS` keys in the secret being updated to empty string. Hence, backend deployment was not correct.
> [FIX] backend redis secret read THREESCALE-3258

- pkg/3scale/amp/operator/zync.go
One time is enough when reading options from secret
> fix zync option reading from operator

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/system.go
Porta should have the defaults rolling updates
See https://github.com/3scale/porta/pull/1234 and https://github.com/3scale/porta/pull/744
This config allows to override those defaults
This does not affect previous behaviour on 2.7 release
Closes https://issues.jboss.org/browse/THREESCALE-2604
> [system] rolling_updates.yml inherits from defaults

- pkg/3scale/amp/operator/redis.go
- pkg/3scale/amp/operator/redis_reconciler.go
- pkg/controller/apimanager/upgrade_26_to_27.go
Database imagestreams are tagged with 3scale release tag names. For instance backend redis imagestream:
```yml
tags:
- annotations:
openshift.io/display-name: Backend 2.6 Redis
from:
kind: DockerImage
name: centos/redis-32-centos7
generation: 2
importPolicy: {}
name: "2.6"
referencePolicy:
type: Source
- annotations:
openshift.io/display-name: Backend Redis (latest)
from:
kind: ImageStreamTag
name: "2.6"
generation: 1
importPolicy: {}
name: latest
referencePolicy:
type: Source
```
To be consistent, upgrade should update those tags, even when image does not change.
Tests have shown that even changing latest tag of the imagestream, deploymentconfigs are not redeployed if image sha remains equal.
Upgrading procedure implemented using reconciliation methods.
> upgrade database imagestreams tagged with 3scale release tag names

- .circleci/config.yml
- test/e2e/apimanager_controller_test.go
- test/e2e/e2eutil/wait.go
This PR adds code in the e2e test that checks that all routes that should be created by default in an APIManager deployment are indeed created
> Add routes checking in e2e tests

- .circleci/config.yml
`vendor` folder should not be cached.
Go modules cache directory should only be cached, i.e. `/go/pkg` folder. 
Same go.sum (same modules and releases) may lead to different `vendor` folder, because vendor only contains used packages, not used modules. `/go/pkg` folder contains used modules and can be identified uniquely by `go.sum`. Does not happen the same with `vendor` folder.
> do not cache vendor folder

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/manual-templates/amp/apicast.yml
- pkg/3scale/amp/product/3scale_release.go
- version/version.go
This PR should be merged just before `2.7-stable` and `2.7-stable-prod` branches are created. Stable branches should start off from the merge commit of this PR.
> Operator version bump 0.4.0

- .circleci/config.yml
- Makefile
- pkg/apis/apps/v1alpha1/apimanager_types.go
- pkg/apis/apps/v1alpha1/apimanager_types_test.go
This PR prepares project to execute unit tests via Makefile and integrated into CircleCI and adds basic unit tests for APIManager types
> Add basic unit test for APIManager types package

- .circleci/config.yml
CircleCI does not run workflows for tags unless you explicitly specify tag filters
https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
> fix circleci tag building

- Makefile
Testing coverage is reduced from ~60% to 40%. However, the total line numbers included in the report is increased from 3k to 10k. So, numbers are more accurate.
> testing coverage report on any package

- cmd/manager/main.go
Update the metrics endpoint in the operator to include operator version and 3scale product version:
```
threescale_version_info{operator_version="0.4.0",version="2.7"} 0
```
> metrics endpoint include 3scale operator and product version

- doc/apimanager-reference.md
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/system_options_builder.go
- pkg/3scale/amp/operator/backend.go
- pkg/3scale/amp/operator/highavailability.go
- pkg/3scale/amp/operator/mysql.go
- pkg/3scale/amp/operator/mysql_test.go
- pkg/3scale/amp/operator/s3.go
- pkg/3scale/amp/operator/s3_test.go
- pkg/3scale/amp/operator/secret_reconciler_test.go
- pkg/3scale/amp/operator/system.go
- pkg/3scale/amp/operator/system_postgresql.go
- pkg/3scale/amp/operator/system_reconciler.go
- pkg/3scale/amp/operator/system_reconciler_test.go
- pkg/3scale/amp/operator/system_test.go
- pkg/3scale/amp/operator/upgrade.go
- pkg/3scale/amp/operator/zync.go
- pkg/controller/apimanager/apimanager_controller_test.go
- pkg/helper/secretutils.go
This PR changes the deployment of the SMTP configuration from a ConfigMap to a Secret.
The reason of this is because some of the configuration contains credentials.
> Move system smtp to secret

- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/system_options_builder.go
- pkg/3scale/amp/operator/system.go
- pkg/3scale/amp/operator/system_mysql_image.go
- pkg/3scale/amp/operator/system_postgresql_image.go
- pkg/3scale/amp/operator/system_reconciler.go
- pkg/3scale/amp/operator/upgrade.go
- pkg/3scale/amp/template/adapters/system.go
- pkg/apis/apps/v1alpha1/apimanager_types.go
- pkg/apis/apps/v1alpha1/apimanager_types_test.go
- pkg/controller/apimanager/apimanager_controller.go
* Fix storageClassName property location
* CR databases defaults cannot be `mysql`. When external databases are configured, this leads to inconsistent information. Changed defaults set for the CR. Mysql is still the *default* database if none configured
* CR storage defaults removed. PVC is still the *default* storage if none configured
* Upgrade procedure to remove databases and storage defaults
> storage and database defaults refactor

- doc/apimanager-reference.md
- doc/operator-user-guide.md
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/component/s3.go
- pkg/3scale/amp/component/s3_options_builder.go
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/template/adapters/s3.go
New env var for system-app:
`AWS_PATH_STYLE: Default: false - When set to true, the bucket name is always left in the request URI and never moved to the host as a sub-domain`
> Aws path style envvar

- doc/template-user-guide.md
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/images.go
- pkg/3scale/amp/manual-templates/amp/apicast.yml
APIcast component is now based on RHEL8 and the URL has changed
> Update apicast image rhel8

- go.mod
The expected language version, set by the go directive, determines
which language features are available when compiling the module.
Language features available in that version will be available for use.
Language features removed in earlier versions, or added in later versions,
will not be available. Note that the language version does not affect
build tags, which are determined by the Go release being used.
One of the motivations of this change is that later Go versions automatically
add the directive in the go.mod file if it is not set previously. By
explicitely setting it we ensure that this does not happen.
It is important to remark that this directive does NOT set the minimum version
or maximum version allowed to compile. It specifies which language features are available
to the code. …
> Set expected go version in go.mod to 1.12

- .circleci/config.yml
Adds a command in CircleCI that checks the existence of the default routes that should be created when deploying 3scale.
It has been added into the nightly templates deployment and the one that is executed in each PR.
> Add routes existence tests in templates deployments

- .circleci/config.yml
- doc/development.md
- go.mod
Since operator-sdk v0.12.0 minimum Go version for operator-based projects is Go 1.13.x https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md#changed-5
> Bump minimum Go version to 1.13.x

- pkg/3scale/amp/operator/ampimages.go
- pkg/3scale/amp/operator/images.go
- pkg/3scale/amp/operator/images_test.go
- pkg/3scale/amp/operator/redis.go
- pkg/3scale/amp/operator/system_mysql_image.go
- pkg/3scale/amp/operator/system_postgresql_image.go
Disconnected install required all operands to be referenced by sha digest urls
> missing image urls from env vars

- deploy/olm-catalog/3scale-operator-master/3scale-operator-master.v0.0.0.clusterserviceversion.yaml
- pkg/3scale/amp/operator/ampimages.go
- pkg/3scale/amp/operator/images.go
- pkg/3scale/amp/operator/images_test.go
- pkg/3scale/amp/operator/redis.go
- pkg/3scale/amp/operator/system_mysql_image.go
- pkg/3scale/amp/operator/system_postgresql_image.go
Disconnected install required all operands to be referenced by sha digest urls
> Backport missing images envvars

- .circleci/config.yml
Following guidelines (but for Go 1.13.7 where go modules is by default on)
https://circleci.com/blog/go-v1.11-modules-and-circleci/
> enabling go modules circleci

- Makefile
Tired of doing `make clean unit`
`make unit` should be enough
> unit makefile target always cleans first

- .circleci/config.yml
- pkg/3scale/amp/manual-templates/amp/build.yml
Since PR https://github.com/3scale/3scale-operator/pull/292 ImageStreams are no longer created with the "latest" tag but with the version-specific tag.
CircleCI tasks that relied on ImageStream building via the build.yml template to create the ImageStreams independently were always being created with "latest" tags.
This PR makes the name of the ImageStream tags of the 3scale components configurable in the build.yml and updates CircleCI jobs that rely on them to use the version-specific tag. In the case of this PR, "master".
> Fix CI jobs that create the ImageStreams separately

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/apicast.go
- pkg/3scale/amp/component/apicast_options.go
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/system_options.go
- pkg/3scale/amp/operator/apicast_options_provider.go
- pkg/3scale/amp/operator/apicast_options_provider_test.go
- pkg/3scale/amp/operator/system_options_provider.go
- pkg/3scale/amp/operator/system_options_provider_test.go
- pkg/3scale/amp/operator/upgrade.go
- pkg/3scale/amp/template/adapters/apicast.go
- pkg/3scale/amp/template/adapters/system.go
Simplifying `system-master-apicast` secret and apicast options structure. Master base Url not required.
> Fix apicast 3scale portal endpoint

- Makefile
CircleCi workflow run unittests and then reported coverage. 
This PR prevents unittests output from being deleted.
> Fix coverage report

- doc/apimanager-reference.md
The S3 storage table was broken.  It's now fixed.
> Fixed formatting of the S3 table

- doc/apimanager-reference.md
- doc/operator-user-guide.md
Some deprecated field names documentation update in the user-guide (they were in the reference) were not backported into the 3scale-2.8-stable-prod
This PR Backports #314
> backport 3scale-2.8-stable-prod #314 Update s3 fields in user guide

- .circleci/config.yml
- pkg/3scale/amp/manual-templates/amp/build.yml
Changes the image of the base ImageStream used by the zync BuildConfig from `centos/ruby-24-centos7` to `registry.access.redhat.com/ubi7/ruby-25`. This not only changes the underlying operating system to RHEL7, but also upgrades Ruby to 2.5.
This change follows https://github.com/3scale/zync/pull/328, which aligned the recommended settings for building Zync in Opesnhift with its current Dockerfile in the upstream and Ruby version upon which CI tests are run and downstream images are built.
I understand this will change the nightly builds, making them aligned to current development stage of the upstream. https://github.com/3scale/3scale-operator/blob/cc029c11494d99c91fb94e9778fb6a713373dfa7/.circleci/config.yml#L226.
> Zync BuildConfig with UBI7 base image

- pkg/3scale/amp/manual-templates/amp/build.yml
Image builder also needs pullsecret to access private repos.
> add pullSecret to buildconfig to access private repos

- .circleci/config.yml
- deploy/operator.yaml
- test/e2e/apimanager_controller_test.go
Production urls are only valid after GA. Before GA, production urls will return 404 Not found because it is on GA when images are made public.
So before GA, the operator stable branch should be using 3scale operand images from the component's stable branches. Even nightly images are wrong. That is because some component could be merging to master some new feature (maybe breaking thing) just after creating component's stable branch.
After GA, before any update in the operator code, the stable branch of the operator should be updated with a PR like this. That is the main reason of this PR.
> Use public images for tests

- deploy/role.yaml
- doc/apimanagerrestore-reference.md
- doc/operator-backup-and-restore.md
- pkg/controller/apimanagerrestore/apimanagerrestore_logic_reconciler.go
- pkg/restore/apimanager_restore.go
This PR adds the following:
* Waits until APIManager resource has all non-external Deployments in "ready" state.
* Trigger of zync domains resync via a Kubernetes Job
This PR is built on top of PR https://github.com/3scale/3scale-operator/pull/358 and the base merge branch is the one from that PR.
We also should evaluate/consider whether we want to include the functionality in the restore itself. Doing so implies that the restore does not finish until the deployments are ready (it keeps waiting) and the domains resync finishes without an exit code error
> Add restore wait for apimanager readiness and resync of zync routes

- deploy/operator.yaml
- pkg/3scale/amp/component/images.go
- pkg/backup/apimanager_backup.go
- pkg/backup/apimanager_backup_options.go
- pkg/backup/apimanager_backup_options_provider.go
- pkg/restore/apimanager_restore.go
- pkg/restore/apimanager_restore_options.go
- pkg/restore/apimanager_restore_options_provider.go
Currently backup/restore K8s Jobs use the hardcoded `registry.redhat.io/openshift4/ose-cli:4.2` image.
Update code to make the image configurable through an environment variable.
This change will allow us to configure a productized environment where direct SHA images are used in order to be able to support disconnected installs.
The PR also changes the default image to `quay.io/openshift/origin-cli:4.2` which is the upstream version of the cli image. When creating the productized branch of the operator and when productizing the operator manifests we should update values of the image to the productized image `registry.redhat.io/openshift4/ose-cli:4.2`
> Make OC CLI Image configurable in backup/restore

- pkg/reconcilers/base_reconciler.go
ObjectInfo is often empty when calling GetResource so the logging of the object's name and namespace ended up often being empty
> Update GetResource to get namespacedname info from the ObjectKey

- pkg/backup/apimanager_backup.go
- pkg/backup/apimanager_backup_options.go
- pkg/backup/apimanager_backup_options_provider.go
To provide contextual information to the backup PVC. Useful in the case APIManagerBackup CR is deleted to still have some information regarding where that PVC came from.
> Add APIManagerBackup information in destination backup PVC annotations

- deploy/crds/apps.3scale.net_apimanagerbackups_crd.yaml
- deploy/crds/apps.3scale.net_apimanagerrestores_crd.yaml
- doc/operator-backup-and-restore.md
- pkg/apis/apps/v1alpha1/apimanagerbackup_types.go
- pkg/apis/apps/v1alpha1/apimanagerrestore_types.go
- pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/apps/v1alpha1/zz_generated.openapi.go
- pkg/controller/apimanagerbackup/apimanagerbackup_logic_reconciler.go
- pkg/controller/apimanagerrestore/apimanagerrestore_logic_reconciler.go
- pkg/reconcilers/base_reconciler.go
Volumes that are mounted in the Backup/Restore jobs (like system-storage) cannot be deleted even if the jobs (and its pods) are in 'Completed' state.
This prevented the full deletion of an APIManager object while an APIManagerBackup existed.
Add a step that cleanups the K8s jobs.
> Add step to cleanup Backup/Restore K8s jobs

- pkg/backup/apimanager_backup.go
- pkg/helper/job.go
- pkg/restore/apimanager_restore.go
- pkg/restore/apimanager_restore_options.go
- pkg/restore/apimanager_restore_options_provider.go
Until now K8s Job names created by APIManagerBackup and APIManagerRestore controllers were created using the APIManagerBackup/Restore CR name as part of the K8s Job and a unique job suffix. This was done in order to have predictable Job names and with multiple existing APIManagerBackup/APIManagerRestore CR objects at the same time.
The problem with that approach is that the size of the name of the resulting K8s was depending on the CR name length that the user provided when creating the CRs. K8s labels have a limitation of 63 characters and the combination of the CR name + the unique job suffix made K8s Job names reach the limit of characters for labels in some occasions.
The new approach creates K8s job names based on a prefix job name (defined by us in code) and the UID of the …
> Create APIManagerBackup/Restore unique predictable K8s job names from CRs UIDs

- pkg/apis/apps/v1alpha1/apimanager_types.go
It does not change existing behaviour due to omitempty automatically
implies optional but it's still recommended the optional comment
tag to be added
> Add optional comment tag to system's appspec and sidekiqspec

- pkg/helper/labels.go
Fix error about Reconciler error in SHA-based deployment
https://issues.redhat.com/browse/THREESCALE-5476
> Metering labels validate label max length

- doc/monitoring-stack-deployment/3scale-scrape-configs.yaml
- doc/monitoring-stack-deployment/README.md
- doc/monitoring-stack-deployment/datasource.yaml
- doc/monitoring-stack-deployment/grafana.yaml
- doc/monitoring-stack-deployment/prometheus.yaml
- doc/operator-monitoring-resources.md
Monitoring stack setup is beyond 3scale operator responsibility. 
* Document 3scale operator monitoring requirements from the monitoring stack.
* Monitoring stack deployment steps and templates for devtesting purposes
> doc monitoring stack

- .circleci/config.yml
Latest release is 2.1.8 which has a bug being fixed https://github.com/operator-framework/operator-courier/pull/189
Set specific version
> set operator courier version for tests

- pkg/apis/capabilities/v1beta1/product_types.go
- pkg/apis/capabilities/v1beta1/product_types_test.go
- pkg/controller/backend/backend_controller.go
- pkg/controller/product/product_controller.go
3scale API ignores case of the `system_name` field.
The operator will transform to lower case to avoid confusion and conflict with other existing product with the same system_name when all chars are lowercase.
> product CRD: system name to lower case

- pkg/apis/capabilities/v1beta1/backend_types.go
- pkg/controller/backend/3scale_reconciler.go
- pkg/controller/backend/backend_controller.go
* backend controller: fix handle err
* backend controller: system name to lower case: 3scale API ignores case of the system_name field. The operator will transform to lower case to avoid confusion and conflict with other existing product with the same system_name when all chars are lowercase.
> Fix backend sync

- pkg/apis/capabilities/v1beta1/backend_types.go
- pkg/controller/backend/3scale_reconciler.go
- pkg/controller/backend/backend_controller.go
* Backend controller: fix handle err
* Backend controller: system name to lower case: 3scale API ignores case of the system_name field. The operator will transform to lower case to avoid confusion and conflict with other existing product with the same system_name when all chars are lowercase.
> [Backport 433] Fix backend controller

- doc/apimanagerbackup-reference.md
- doc/operator-backup-and-restore.md
- doc/operator-user-guide.md
This PR updates APIManagerBackup documentation to clarify PV pre-binding usage.
When providing a pre-existing PersistentVolume to APIManagerBackup
resources still have to be defined as per K8s PVCs behavior.
This commit updates the APIManagerBackup reference documentation
and deployment examples to specify and clarify this behavior which
might be surprising but that is how PVCs specification in K8s
requires and behaves.
Details about this behavior in: https://issues.redhat.com/browse/THREESCALE-5677
> Update APIManagerBackup PVC requirements documentation

- deploy/crds/capabilities.3scale.net_backends_crd.yaml
- deploy/crds/capabilities.3scale.net_products_crd.yaml
- pkg/apis/capabilities/v1beta1/backend_types.go
- pkg/apis/capabilities/v1beta1/product_types.go
- pkg/controller/backend/backend_controller.go
- pkg/controller/backend/status_reconciler.go
- pkg/controller/product/product_controller.go
- pkg/controller/product/status_reconciler.go
Add provider account host url in status for `Backend` and `Product` CRD's.
As example, check `providerAccountHost` field in status object
```
apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
name: backend-a
namespace: eguz
spec:
...
status:
backendId: 61535
providerAccountHost: https://3scale-supertest-admin.3scale.net
```
> Capabilities provider account status

- pkg/3scale/amp/component/system.go
As reported by our QE team and confirmed by System team ORACLE_SYSTEM_PASSWORD is needed in system-app's post-hook pod when Oracle is to be used.
> Add ORACLE_SYSTEM_PASSWORD optional enviornment variable to system-app pre-hook pod

- deploy/crds/capabilities.3scale.net_products_crd.yaml
- pkg/apis/capabilities/v1beta1/product_types.go
The original regular expression, that I understand was intended to validate a floating point number with optionally two decimal numbers exactly was not validating that specification.
This PR fixes the regular expression to validate it.
This applies to pricePerUnit, setupFee and costMonth fields
> Fix regex validation in Product type for fields that specify USD

- deploy/crds/capabilities.3scale.net_backends_crd.yaml
- deploy/crds/capabilities.3scale.net_products_crd.yaml
- doc/backend-reference.md
- doc/product-reference.md
- pkg/apis/capabilities/v1beta1/product_types.go
- pkg/apis/capabilities/v1beta1/zz_generated.deepcopy.go
- pkg/controller/backend/3scale_reconciler.go
- pkg/controller/product/mapping_rules.go
Add the optional 'last' attribute in MappingRules for Products and Backends
> Add configurable 'last' attribute in mapping rules

- deploy/crds/apps.3scale.net_apimanagers_crd.yaml
- doc/apimanager-reference.md
- doc/operator-user-guide.md
- pkg/3scale/amp/operator/apicast_options_provider.go
- pkg/3scale/amp/operator/apicast_options_provider_test.go
- pkg/3scale/amp/operator/backend_options_provider.go
- pkg/3scale/amp/operator/backend_options_provider_test.go
- pkg/3scale/amp/operator/memcached_options_provider.go
- pkg/3scale/amp/operator/memcached_options_provider_test.go
- pkg/3scale/amp/operator/redis_options_provider.go
- pkg/3scale/amp/operator/redis_options_provider_test.go
- pkg/3scale/amp/operator/system_mysql_options_provider.go
- pkg/3scale/amp/operator/system_mysql_options_provider_test.go
- pkg/3scale/amp/operator/system_options_provider.go
- pkg/3scale/amp/operator/system_options_provider_test.go
- pkg/3scale/amp/operator/system_postgresql_options_provider.go
- pkg/3scale/amp/operator/system_postgresql_options_provider_test.go
- pkg/3scale/amp/operator/zync_options_provider.go
- pkg/3scale/amp/operator/zync_options_provider_test.go
- pkg/apis/apps/v1alpha1/apimanager_types.go
- pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
This PR adds configurable resource requirements for APIManager components.
* Configurable resource requirements per component has been added
* When resource requirements are not specified at component level the global defaults for the component are used for it (if enabled)
* When resource requirements are specified at component level, they take over preference over the global default and they follow a REPLACE behaviour (instead of merge behaviour) with the defaults.
* global-level defaults for resource limits and requests for the components of 3scale are provided. This global-level defaults can be enabled or disabled through a CR attribute that already existed before this PR, named 'resourceRequirementsEnabled'.
* component-level *resources* attribute is provided at component level (for …
> Configurable resource requirements for APIManager components

- pkg/3scale/amp/manual-templates/amp/build.yml
We are moving the Dockerfile.on_prem to Dockerfile
Requires: https://github.com/3scale/porta/pull/2132
> [system] Use the only unique Dockerfile for nightly build

- deploy/olm-catalog/3scale-operator-master/0.0.0/3scale-operator-master.v0.0.0.clusterserviceversion.yaml
- deploy/operator.yaml
Jira Issue: https://issues.redhat.com/browse/THREESCALE-5860
What
----------
Currently, no requests or limits for CPU and memory are set for the 3scale operator.
Current QoS class
Best Effort
How
------
Requests and limits for CPU and memory should be set in the operator deployment which will be used for the CSV generation.
> operator deployment resource requests

- pkg/apis/capabilities/v1beta1/product_types.go
- pkg/controller/backend/3scale_reconciler.go
- pkg/controller/backend/backend_controller.go
- pkg/controller/helper/backend_list.go
- pkg/controller/helper/product_list.go
- pkg/controller/product/product_controller.go
- pkg/helper/slice_string_utils.go
When backend metric or method is deleted, Application plan limits and pricing rules with references to it have to be deleted also, as it happens automatically in the System UI.
Fixes [issue](https://issues.redhat.com/browse/THREESCALE-5534) about product and backend consistency when there are references between them.
> capabilities: reconciliate product on backend metric deletion

- pkg/controller/backend/backend_controller.go
- pkg/controller/product/product_controller.go
product, backend controllers: fix nil pointer when provider account not found
>  fix nil pointer when provider account not found

- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/system_monitoring.go
- pkg/3scale/amp/component/system_options.go
- pkg/3scale/amp/operator/system_options_provider.go
- pkg/3scale/amp/operator/system_options_provider_test.go
- pkg/3scale/amp/operator/system_reconciler.go
- pkg/3scale/amp/operator/upgrade.go
This PR adds Prometheus Monitoring for system-app containers.
The expected environment variables and port numberings for system-app containers Prometheus functionality has been defined in https://github.com/3scale/3scale-operator/issues/453. This PR uses thoses values.
> Add system-app prometheus monitoring

- doc/apimanager-reference.md
apicast does not make use of redis anymore. That part of
the documentation was outdated in that regard.
> Update documentation to remove apicast redis reference

- .circleci/config.yml
In CircleCI the following error is sometimes shown when checking the DeploymentConfig status for the deployed DeploymentConfigs when using templates:
```
error: .status.conditions accessor error: Failure is of the type string, expected map[string]interface{}
```
An example execution of this can be found in:
https://app.circleci.com/pipelines/github/3scale/3scale-operator/2542/workflows/9f1eadf8-6999-4456-81ca-59ba844a18e8/jobs/17680
This makes our CI runs fail with on several occasions.
After looking at this issue, it seems that that error is shown when a DeploymentConfig does not have the 'Available' status condition defined yet (it is not defined in the status conditions array, nor with true or false value).
An example to reproduce this is to specify an unexisting condition name in the …
> Improve CI templates DeploymentConfig status state checks

- pkg/3scale/amp/component/apicast_monitoring.go
- pkg/3scale/amp/component/system_monitoring.go
Solves part of https://github.com/3scale/platform/issues/355
Severity `critical` must be configured on very important alerts with customer impact, they are the ones paging oncall SRE, so there is needed a very good reason to be treated as `critical` (at least on the default values).
For that reason, it has been updated severity on some alerts (from `critical` to `warning`):
- **ThreescaleApicastHttp4xxErrorRate**: after agreed with @eloycoto, having a high number of 4XX http requests can occur by many reasons (auth is not valid, service is not being found, mapping rule does not exists, upstream is sending a 4XX status code, used policy is configured to send 4XX status code), most of them should never be treated as a `critical` alert
- **SystemSidekiqZyncRuntime**: this is just an example …
> Update severity of some 3scale prometheus alerts

- .circleci/config.yml
As per https://discuss.circleci.com/t/old-linux-machine-image-remote-docker-deprecation/37572, some linux machine images have been deprecated in CircleCI
This PR updates the deprecated `circleci/classic:latest` images by `ubuntu-1604:202007-01` as suggested in the provided link. There's also an ubuntu 20 based image but is still in beta so we are not using it yet.
The update of image implies an update of operating system from Ubuntu 14.04 to Ubuntu 16.04.
> Update deprecated CircleCI images

- pkg/3scale/amp/component/apicast_monitoring.go
As requested in https://issues.redhat.com/browse/THREESCALE-6047.
I've adapted the provided alert with some filtering changes and naming changes
> Add APIcast workers monitoring alert

- deploy/crds/capabilities.3scale.net_products_crd.yaml
CRD Openapi custom validation added.
it is deleted by `operator-sdk generate crds` and must be maintained manually. Very easy to get lost.
> products CRD openapi missing validation added

- pkg/3scale/amp/operator/base_apimanager_logic_reconciler.go
> Fix monitoring logging typo in APIManager base logic reconciler

- controllers/apps/apimanager_controller_test.go
- controllers/apps/suite_test.go
This PR fixes some bugs on the APIManager controller e2e tests:
* Consider all APIManager managed DCs
* Re-enables waiting for OCP Routes and adapts it to new operator-sdk version used testing framework
> Fix APIManager controller e2e tests

- bundle/manifests/apps.3scale.net_apimanagerbackups.yaml
- bundle/manifests/apps.3scale.net_apimanagerrestores.yaml
- bundle/manifests/apps.3scale.net_apimanagers.yaml
- bundle/manifests/capabilities.3scale.net_backends.yaml
- bundle/manifests/capabilities.3scale.net_openapis.yaml
- bundle/manifests/capabilities.3scale.net_products.yaml
- bundle/manifests/capabilities.3scale.net_tenants.yaml
- config/crd/kustomization.yaml
- config/crd/patches/additional_app_label_in_crds.yaml
Adds the 'app' label to 3scale CRDs with value `3scale-api-management`. The chosen value is the same as the default 'app' label value when an APIManager CR is created (although there it can be changed by the user).
operator-sdk and kubebuilder do not provide a way to set the label through any marker so a patch to include the label has been needed.
I've observed in kustomize there's a global variable named `commonLabels` but that adds the labels to all objects, not to just CRDs and also adds it to selectors so that option has not been chosen.
> Add app label to 3scale CRDs

- controllers/apps/apimanager_controller.go
- pkg/3scale/amp/operator/base_apimanager_logic_reconciler.go
- pkg/3scale/amp/operator/base_apimanager_logic_reconciler_test.go
- pkg/reconcilers/base_reconciler.go
- pkg/reconcilers/base_reconciler_test.go
I detected reconciliation times for APIManager were abnormally long.
This PR improves the time it takes to perform a reconciliation event from 1.5 minutes to 2-3 seconds approximately (a 96.7%  reduction approximately)
After investigating the issue I noticed that reconciliation was taking abnormally long time in the APIManager controller. After measuring it I observed it was taking abnormally long times:
```
2020-11-17T14:42:13.952+0100	INFO	controllers.APIManager	Full reconciliation took 1m33.955830582s
```
Going into a little bit more of detail I observed that the cause of this long execution times was due to the requests we do to check whether monitoring CRDs exist or not via the K8s DiscoveryClient. This was introduced when monitoring functionality was added into the operator. This …
> Improve APIManager reconcile times

- doc/apimanager-reference.md
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/apicast.go
- pkg/3scale/amp/component/backend_options.go
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/system_options.go
- pkg/3scale/amp/operator/system_options_provider.go
- pkg/3scale/amp/operator/system_options_provider_test.go
- pkg/3scale/amp/operator/upgrade.go
- pkg/3scale/amp/template/adapters/system.go
Recently, it was merged in Porta [this PR](https://github.com/3scale/porta/pull/2268) 
Now, they are respecting the `BACKEND_ROUTE` env var set in deployment. 
Before, Porta was reading some unset env var `THREESCALE_CORE_INTERNAL_API` and it did not exist, so they were using as backend route: `http://backend-listener:3000/internal/`. It worked as expected. 
But now, as `BACKEND_ROUTE` env var is respected, in 3scale operator CI, 3scale system tries to connect to `https://backend-3scale.lvh.me`, and ovbiously, it fails. 
```
Errno::ECONNREFUSED: Connection refused - connect(2) for "backend-3scale.lvh.me" port 443
/opt/system/vendor/bundle/ruby/2.5.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:692:in `start'
/opt/system/vendor/bundle/ruby/2.5.0/gems/net-http-persistent-3.0.0/l …
```
> Fix system env var backend route

- pkg/3scale/amp/operator/upgrade.go
When monitoring was disabled, the operator still tried to fetch monitoring resources, which were expected to exist. 
This PR frees the upgrade procedure from upgrading monitoring resources. 
However, the operator still upgrades deployment config env vars for monitoring ports (for system components)
> fix upgrade when monitoring is disabled

- .circleci/config.yml
Generalize circleci tests for:
* e2e test to be passed for any 3scale component tag
* 3scale image builds for any 3scale component tag
Useful in (future) stable branches to specify tag for e2e tests.
> Generalized circleci e2e tests and builds for any tag

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/zync.go
- pkg/3scale/amp/operator/upgrade.go
Zync DeploymentConfig had the following annotations defined as part of the DC annotations:
```
annotations:
prometheus.io/port: "9393"
prometheus.io/scrape: "true"
```
They should belong to Zync's PodTemplate annotations and not Zync's DC annotations themselves.
This does not affect operator monitoring functionality because we use `PodMonitor` there but we should fix this anyway (it's provided in templates too and there there's no CRs)
This PR takes care of changing that.
Related issue: https://issues.redhat.com/browse/THREESCALE-6509
> Fix Zync monitoring annotations location

- pkg/3scale/amp/component/apicast_monitoring.go
- pkg/3scale/amp/component/apicast_options.go
- pkg/3scale/amp/component/backend_monitoring.go
- pkg/3scale/amp/component/backend_options.go
- pkg/3scale/amp/component/generic_monitoring.go
- pkg/3scale/amp/component/system_monitoring.go
- pkg/3scale/amp/component/system_options.go
- pkg/3scale/amp/component/zync_monitoring.go
- pkg/3scale/amp/component/zync_options.go
- pkg/3scale/amp/operator/apicast_options_provider.go
- pkg/3scale/amp/operator/apicast_options_provider_test.go
- pkg/3scale/amp/operator/apicast_reconciler.go
- pkg/3scale/amp/operator/backend_options_provider.go
- pkg/3scale/amp/operator/backend_options_provider_test.go
- pkg/3scale/amp/operator/backend_reconciler.go
- pkg/3scale/amp/operator/generic_monitoring_reconciler.go
- pkg/3scale/amp/operator/system_options_provider.go
- pkg/3scale/amp/operator/system_options_provider_test.go
- pkg/3scale/amp/operator/system_reconciler.go
- pkg/3scale/amp/operator/zync_options_provider.go
- pkg/3scale/amp/operator/zync_options_provider_test.go
- pkg/3scale/amp/operator/zync_reconciler.go
- pkg/3scale/amp/template/adapters/apicast.go
- pkg/3scale/amp/template/adapters/backend.go
- pkg/3scale/amp/template/adapters/system.go
- pkg/3scale/amp/template/adapters/zync.go
https://issues.redhat.com/browse/THREESCALE-6496
The PR adds more labels to existing list of labels. Thus, upgrade procedure is not needed, as first reconciliation loop will add missing labels.
> Add more labels to monitoring resources

- go.mod
- go.sum
Upgrading to [containerd v1.3.9](https://github.com/containerd/containerd/releases/tag/v1.3.9) which includes a security release to address CVE-2020-15257
> Upgrade containerd dep cve 2020 15257

- go.mod
- go.sum
Upgrading to [containerd v1.3.9](https://github.com/containerd/containerd/releases/tag/v1.3.9) which includes a security release to address CVE-2020-15257
Backport from #558
> [backport] upgrade containerd with a security release to address CVE-2020-15257

- Makefile
- main.go
* `make run` will run in development mode with DEBUG log enabled
* operator deployed by deployment manifests will not run in dev mode.
> development mode running controlled by flag

- .circleci/config.yml
- Makefile
- doc/development.md
CircleCI job to build 3scale components images and push to quay.io image repo. Includes Makefile target to make it easy to trigger building job.
Depends on https://github.com/3scale/3scale-operator/pull/554. Needs to be merged after.
> Circleci trigger image build workflow

- controllers/apps/apimanager_controller.go
- pkg/handlers/apimanager_managed_routes_event_mapper.go
This PR contains a possible implementation on how to detect changes that happen on `Route` objects that are automatically created by Zync when an APIManager installation is performed. This needs additional specific logic because Zync-managed routes do not contain an OwnerReference to an APIManager, so the common `EnqueueRequestForOwner` handler cannot be used.
It also implements remapping directly owned APIManager Route events to APIManager events (like the `backend` route).
The approach that this PR follows is based on the K8s `EventHandler` mechanism (https://godoc.org/sigs.k8s.io/controller-runtime/pkg/handler#EventHandler):
* A new mapper named `APIManagerRoutesEventMapper` has been implemented and it watches changes of `Route` objects in the namespace. When those `Route` object …
> Add EventHandler that remaps APIManager-based Route events to APIManager events

- controllers/apps/apimanager_controller_test.go
- controllers/apps/suite_test.go
- controllers/capabilities/suite_test.go
This changes the E2E tests execution to deploy an APIManager using System's FileStorage as S3 instead of a PVC.
The motivation of this change is to be able to deploy them in a cluster environment that does not provide RWX volumes, which is required by System's FileStorage.
The provided S3 data for the E2E tests is fake data, as it's not needed for the kind of tests we are performing at the moment. In case there's some test functionality that we end up doing that exercises S3 then additional changes will need to be done or change the provided approach.
> APIManager e2e tests with S3

- Makefile
- controllers/apps/apimanager_suite_test.go
- controllers/apps/suite_test.go
- controllers/capabilities/suite_test.go
- test/unitcontrollers/apimanager_controller_test.go
* Specific test suite for apimanager. Improved test logs
```
=== RUN   TestAPIManager
Running Suite: APIManager Controller Suite
==========================================
Random Seed: 1611753802
Will run 2 of 2 specs
STEP: bootstrapping test environment
```
* REmove test only packages from coverage base
> Test suite little fixes

- pkg/3scale/amp/operator/base_apimanager_logic_reconciler.go
- pkg/3scale/amp/operator/highavailability_reconciler_test.go
- pkg/3scale/amp/operator/upgrade.go
The reason for this is that secrets are often managed by users and users
sometimes manage the secrets themselves by other controllers which also
add controller-based OwnerReferences to the secrets.
In K8s only a single controller-based OwnerReference is allowed per object, which
was preventing users to work with their own controller-based secrets.
An implication of this change is that the responsibility to cleanup
the APIManager secrets deployed belongs to the user.
This changes include an upgrade procedure to remove the APIManager
controller-based ownerReferences from existing APIManager
secrets.
> apimanager: Do not set APIManager controller-based ownerReferences on Secrets

- pkg/3scale/amp/manual-templates/amp/build.yml
Update apisonator dockerfile path, as it was changed in https://github.com/3scale/apisonator/pull/268
> apisonator build uses new dockerfile based on ubi8

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/capabilities/activedoc_controller.go
- controllers/capabilities/custompolicydefinition_controller.go
- controllers/capabilities/developeraccount_controller.go
- controllers/capabilities/developeruser_controller.go
This PR fixes CRD role permissions level from ClusterRole to Role for ActiveDocs, DeveloperAccount, DeveloperUser and CustomPolicyDefinition(formerly Policy) CRDs.
By default operator-sdk generates the roles for the CRDs as ClusterRoles unless the 'namespace' attribute in the role permissions annotations appears there. This was not done for the CRDs mentioned above causing the incorrect cluster level permissions to be generated.
Changes have been performed in the controller files where role permission annotations are defined and manifests and bundle have been regenerated
> Fix CRD role permissions level for some CRDs

- .circleci/config.yml
- Makefile
- pkg/assets/assets.go
- pkg/assets/bindata.go
There is no magic. assets have to be generated with the go-bindata tool. The asset generation is added to the `generate` makefile target.
In this PR I learnt that the generated code does not change each time you execute go-bindata. There will be changes in the generated code if template file modification times or content is changed. The file modification times are changed each time the project is cloned. In order to avoid this behavior, adding `-nometadata` to the generate command to not preserve size, mode, and modtime info
> Fix go bindata assets

- doc/apimanager-reference.md
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/system_options.go
- pkg/3scale/amp/operator/system_options_provider.go
- pkg/3scale/amp/operator/system_options_provider_test.go
Make the 'from' address value of the noreply mail address configurable.
This is an operator-only functionality.
In system, the `NOREPLY_EMAIL` environment variable is used to set the 'from' address of the noreply mail. The behavior in system with this environment variable currently is:
* If the environment variable is defined then its value is used. If it is defined as the empty string `""` that value is literally used instead of a default one
* If the environment variable is not defined then a default value specified by system is used.
All SMTP-related settings are stored in the `system-smtp` Secret. This PR adds the ability to
set the field `from_address` in the `system-smtp` secret. The field value must be set before deploying the APIManager in case the user wants a non-default …
> Add configurable noreply FROM mail address

- go.mod
- go.sum
> go.mod: Fix CVE-2020-14040

- doc/apimanager-reference.md
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/backend_options.go
- pkg/3scale/amp/operator/upgrade.go
Motivated by issue https://github.com/3scale/3scale-operator/issues/584,
This PR increases the backend-cron memory resource limits from `80Mi` to `150Mi`.
Includes upgrade procedure. The memory limits will be upgraded in the following scenario:
* When `.spec.resourceRequirementsEnabled` is set to `true` and `.spec.backend.cronSpec.resources` is NOT set. In any other cases they will not be upgraded. For example, if the user has overwritten them at `.spec.backend.cronSpec.resources` level or `.spec.resourceRequirementsEnabled` is set to `false`
This will require the writing of an upgrade procedure on the templates side.
> Increase default backend-cron DeploymentConfig memory limits

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/images.go
- pkg/3scale/amp/component/redis.go
- pkg/3scale/amp/operator/redis_options_provider_test.go
- pkg/3scale/amp/operator/upgrade.go
- pkg/3scale/amp/template/adapters/redis.go
This PR implements changing the used backend-redis internal database Redis version from 3.2 to 5.x
This has been done for both templates and operator.
In case of the productized version the image URLs will be different than the upstream ones that are the ones that can be seen in this PR. The productized URLs will be updated/set on the version-specific branch.
In the operator case it also includes upgrade automation to migrate from one version to another. The upgrade migration includes:
* Container image change
* Needed command changes
* PodTemplate label changes
In the templates case upgrade documentation will be needed.
> Update backend-redis internal database version from 3.2 to 5.x

- pkg/3scale/amp/operator/apicast_options_provider_test.go
- pkg/3scale/amp/operator/backend_options_provider_test.go
- pkg/3scale/amp/operator/memcached_options_provider_test.go
- pkg/3scale/amp/operator/redis_options_provider_test.go
- pkg/3scale/amp/operator/system_mysql_options_provider_test.go
- pkg/3scale/amp/operator/system_options_provider_test.go
- pkg/3scale/amp/operator/system_postgresql_options_provider_test.go
- pkg/3scale/amp/operator/zync_options_provider_test.go
Refactors references to component labels values from centralized places in the options_provider_* unit tests
The motivation of this is to avoid having to perform manual patches in this tests files depending on the version branch
> Refactor component labels values retrieval in options providers unit tests

- go.mod
- go.sum
This PR addresses CVE-2020-8912.
All the info about affected dependency and replaced version in https://issues.redhat.com/browse/THREESCALE-5928
After the `replace` directive is added, `go.sum` does not show affected version of the dep. On the other hand, `go mod graph` still shows affected versions of the dep, but according to [this issue](https://github.com/golang/go/issues/40513), code is being replaced.
> go.mod,sum: fix CVE-2020-8912

- pkg/controller/helper/application_plan_entity_test.go
- pkg/controller/helper/backend_list_test.go
- pkg/controller/helper/backendapi_entity_test.go
- pkg/controller/helper/backendapi_remote_index_test.go
- pkg/controller/helper/developeruser_test.go
- pkg/controller/helper/helper_test.go
- pkg/controller/helper/lookup_provider_account_test.go
- pkg/controller/helper/product_entity.go
- pkg/controller/helper/product_entity_test.go
- pkg/controller/helper/product_list_test.go
- pkg/controller/helper/threescale_api_test.go
- pkg/controller/helper/url_test.go
Added unittest coverage for `github.com/3scale/3scale-operator/pkg/controller/helper`
Initially, unittest coverage was **33.8%**
```
$ make coverage_total_report
....
33.8%
```
After this PR, **42.4%**
```
$ make coverage_total_report
....
42.4%
```
> Unit test coverage github.com/3scale/3scale-operator/pkg/controller/helper

- Dockerfile
- Makefile
This PR will allow to build container image
and allow e2e testing on ppc64le architecture
Signed-off-by: Krishna Harsha Voora <krishvoor@in.ibm.com>
> Enable builds/ testing on ppc64le architecture

- Makefile
Install development tools at `${PROJECT_BASE_PATH}/bin`. Avoid conflict with the same development tools for different releases required in other working projects. 
* Operator-sdk
* kustomize
* controller-gen
* go-bindata
> local installation of development tools

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- doc/template-user-guide.md
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/images.go
- pkg/3scale/amp/component/redis.go
- pkg/3scale/amp/operator/upgrade.go
- pkg/3scale/amp/template/adapters/redis.go
This PR implements changing the used system-redis internal database Redis version from 3.2 to 5.x
This has been done for both templates and operator.
In case of the productized version the image URLs will be different than the upstream ones that are the ones that can be seen in this PR. The productized URLs will be updated/set on the corresponding downstream repository branch/es.
In the operator case it also includes upgrade automation to migrate from one version to another. The upgrade migration includes:
* Container image change
* Needed command changes
* PodTemplate label changes
In the templates case upgrade documentation will be needed.
> Update system-redis internal database from 3.2 to 5.x

- .circleci/config.yml
Build fails on apt-get update, some repo updated current state from 'stable' to 'oldstable' and command is failing.
> Fix circleci-update-failure

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- pkg/3scale/amp/operator/upgrade.go
- version/version.go
* operator version bump: 0.9.0
* upgrade procedure reset
> Bump release 2.12

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/system_options.go
- pkg/3scale/amp/operator/system_options_provider.go
- pkg/3scale/amp/operator/system_options_provider_test.go
- pkg/3scale/amp/operator/upgrade.go
- pkg/3scale/amp/prometheusrules/system_app_rules.go
- pkg/3scale/amp/template/adapters/system.go
https://issues.redhat.com/browse/THREESCALE-7427
Upgrade procedure implemented for deleting:
* `AMP_RELEASE` from `system-environment` config map
* `AMP_RELEASE` env var from pre-hook in `system-app` deployment config
* `AMP_RELEASE` env var from all containers in `system-app` deployment config
*  `AMP_RELEASE` env var from in `system-sidekiq` deployment config
> Remove AMP_RELEASE system env var

- pkg/3scale/amp/operator/upgrade.go
Uprading 3scale-operator fails to upgrade from 2.10 to 2.11 is enabled when external databases are enabled and the setting to enable zync external database is enabled too:
```
highAvailability:
enabled: true
externalZyncDatabaseEnabled: true
```
The following operator error logs in a loop can be observed when the upgrade process is triggered:
```
2021-09-03T17:40:32.193+0200	ERROR	controllers.APIManager	Error upgrading APIManager	{"apimanager": "msoriano-test/example-apimanager", "error": "Upgrading images: DeploymentConfig.apps.openshift.io \"zync-database\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
/home/msoriano/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/3scale/3scale-operator/controllers/apps.(*APIManagerReconciler).Reconcile …
```
> fix: Make sure zync-database DeploymentConfig is only upgraded when deployed internally

- pkg/helper/labels.go
- pkg/helper/version_parser.go
- pkg/helper/version_parser_test.go
* Keep backward compat. New unittests added, not updated any existing unittests.
* Full check for valid label value, not only length.
> fix docker image version parser

- doc/openapi-user-guide.md
- doc/operator-application-capabilities.md
Explained how 3scale is configured from the OpenAPI document. Which parts of the OpenAPI document are used, and how, to configure 3scale.
Also added documentation about the minimum OpenAPI Document requried to configure a working 3scale product.
https://issues.redhat.com/browse/THREESCALE-4712
> OpenAPI CRD user guide doc

- apis/apps/v1alpha1/apimanager_types.go
- bundle/manifests/apps.3scale.net_apimanagers.yaml
- config/crd/bases/apps.3scale.net_apimanagers.yaml
- doc/apimanager-reference.md
Rename .spec.openTracing.tracingConfigRef to .spec.openTracing.tracingConfigSecretRef to better indicate that the config to be provided is a K8s secret. Used in APIcast production and staging
> Rename APIcast openTracing.tracingConfigRef to tracingConfigSecretRef

- pkg/controller/helper/threescale_api.go
Currently the http client used for application capabilities was not respecting the http proxy env variables. 
https://pkg.go.dev/net/http#ProxyFromEnvironment
> http client respects http proxy env vars

- Makefile
When running `make install` the apimanager crd fails to upload
```bash
make install
/home/austincunningham/repo-integr8ly/3scale-operator/bin/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/austincunningham/repo-integr8ly/3scale-operator/bin/kustomize build config/crd | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/activedocs.capabilities.3scale.net configured
customresourcedefinition.apiextensions.k8s.io/apimanagerbackups.apps.3scale.net configured
customresourcedefinition.apiextensions.k8s.io/apimanagerrestores.apps.3scale.net configured
customresourcedefinition.apiextensions.k8s.io/backends.capabilities.3scale.net configured …
```
> change the makefile install to use create rather that apply

- doc/apimanager-reference.md
- doc/operator-user-guide.md
- doc/template-user-guide.md
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/highavailability.go
- pkg/3scale/amp/component/highavailability_options.go
- pkg/3scale/amp/component/redis.go
- pkg/3scale/amp/component/redis_options.go
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/operator/highavailability_options_provider.go
- pkg/3scale/amp/operator/highavailability_options_provider_test.go
- pkg/3scale/amp/operator/redis_options_provider.go
- pkg/3scale/amp/operator/redis_options_provider_test.go
- pkg/3scale/amp/operator/upgrade.go
- pkg/3scale/amp/template/adapters/ha.go
- pkg/3scale/amp/template/adapters/redis.go
- pkg/3scale/amp/template/adapters/system.go
This PR removes the usage of System's Redis message bus database from System DCs (DeploymentConfigs).
* Removes all redis message-bus related environment variable references from the following DCs:
* system-app
* system-sidekiq
* system-sphinx
* In case databases deployment mode is internal it removes message-bus related attributes from the system-redis K8s Secret. In case databases deployment mode is external then this attributes remain unchanged.
* Implements an upgrade procedure that performs the previously explained changes
This is done for both operator and templates.
Templates will need an upgrade procedure for this change.
> Remove usage of system redis messagebus from System

- doc/tenant-reference.md
Currently the tenant secret reference is required and the doc says it is optional.
> doc: fix tenant secret being default

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_metrics_patch.yaml
- config/default/manager_webhook_patch.yaml
- config/manager/manager.yaml
Deployment label selector field is inmutable. 3scale operator specific labels were added in #691, effectively changing the existing labels from 2.11.0 to 2.11.1. On upgrade scenarios, OLM will try to patch/update a field that is inmutable. Hence, it fails.
It has already been reported here: https://github.com/operator-framework/operator-lifecycle-manager/issues/952
The fix is about changing the name of the deployment. On upgrade scenarios, OLM will detect the deployment name change and will delete the previous deployment and CREATE (not update or patch) the new deployment with the new labels in the selector successfully.
> Change deployment name workaround immutable fields

- main.go
As per the OAS: https://spec.openapis.org/oas/v3.0.0#data-types
```
the format property is an open string-valued property, and can have any value. Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification.
```
The following openapi Doc schema is not successfully validated:
```yaml
parameters:
- name: customer_uuid
in: query
description: Unique customer identifier to be used for experience customization.
schema:
type: string
format: uuid
```
The error from the operator:
```
spec.openapiRef.secretRef: Invalid value: v1.ObjectReference{Kind:"",
Namespace:"3scale-cand-3", Name:"uberoas3", UID:"", APIVersion:"",
ResourceVersion:"", FieldPath:""}: invalid paths: parameter
"customer_uuid" schema is invalid: Unsupported 'format' value 'uuid'
```
Issue: …
> disable openapi schema format validation

- Makefile
- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- controllers/capabilities/tenant_controller.go
- doc/development.md
- go.sum
Updates: 
* dev OLM deployment in operator-marketplace ns
* Increased Deployment limits to 300Mb. The memory footprint has been increased when deployed in cluster scope
Namespaced scope memory footprint:
> prepare for Cluster scoped operator

- .circleci/config.yml
- .gitignore
Ubuntu 16.04-based image used in circleCI is deprecated and near EOL. Migrating to ubuntu-2004:202201-02
https://circleci.com/blog/ubuntu-14-16-image-deprecation/?mkt_tok=NDg1LVpNSC02MjYAAAGCndaS4T7Scgi7c4rB8r6g0bSsqoPY_E5GHWHcYzyRMlDS4oeY1FBTMWliNblf0MAFDvP7ae5x3Qms-6fj3_3WMthRMTB2AJHtYJnSZeld5tQ
> migrate circleci ubuntu to ubuntu-2004:202201-02

- pkg/3scale/amp/component/apicast.go
- pkg/3scale/amp/component/apicast_options.go
- pkg/3scale/amp/operator/apicast_options_provider.go
- pkg/3scale/amp/operator/apicast_options_provider_test.go
- pkg/3scale/amp/operator/apicast_reconciler.go
- pkg/3scale/amp/prometheusrules/apicast_rules.go
- pkg/3scale/amp/template/adapters/apicast.go
The following APIManager fields are not reconciled. 
* `spec.apicast.managementAPI`
* `spec.apicast.openSSLVerify`
* `spec.apicast.responseCodes`
The root reason is that those fields in the APIMamanger CR are reconciled in the `apicast-environment` config map. Then the apicast production and staging deploymentconfigs have env vars as references to fields from that config map. When the APIManager CR fields are changed, the config map is changed, but the apicast deployments are not rolled out, so changes do not take effect. 
This PR makes apicast deployments being rolled out when those APIManager CR fields change their value.
The ideal fix would be to simplify the deployment. The env var defined in the deploymentconfig object should be set with the value of the APIManager CR. This fix makes …
> Reconcile apicast environment

- apis/capabilities/v1alpha1/tenant_types.go
- controllers/capabilities/tenant_controller.go
- controllers/capabilities/tenant_internal_reconciler.go
The Tenant CRD has three fields of SecretReference type. If the `Namespace` is not set in the custom resource, the tenant controller should default that value to the custom resource's namespace.
Deploy 3scale with APIManager CR
```yaml
metadata:
spec:
wildcardDomain: example.com
system:
fileStorage:
name: aws-auth
```
Then create one tenant with secret references without namespace
```yaml
apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
name: ecorp-tenant
spec:
username: admin
systemMasterUrl: https://master.example.com
email: admin@example.com
organizationName: ECorp
masterCredentialsRef:
name: system-seed …
```
> tenant controller: secrets default namespace is the tenant's one

- doc/template-user-guide.md
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/images.go
- pkg/3scale/amp/component/system_mysql.go
- pkg/3scale/amp/operator/upgrade.go
The change of image also implies an automated upgrade from
MySQL 5.7 to 8.0 when coming from an older 3scale installation
where 5.7 is used. There is no need for a custom upgrade procedure.
The data migration is performed automatically when changing the image.
On the product side, the image to be set will be:
`registry.redhat.io/rhscl/mysql-80-rhel7:8.0`
JIRA: https://issues.redhat.com/browse/THREESCALE-7786
which depends on https://issues.redhat.com/browse/THREESCALE-6825
Deploy 3scale with the APIManager
```yaml
k apply -f - <<EOF
metadata:
name: apimanager
spec:
wildcardDomain: ns.apps.example.com
```
Wait for the deployment to be ready
```
oc wait --for=condition=available apimanager/apimanager --timeout=-1s
```
Check mysql 8 is …
> Update system-mysql internal DB from MySQL 5.7 to 8.0

- controllers/capabilities/tenant_internal_reconciler.go
- pkg/controller/helper/tenant.go
Jira Issue: https://issues.redhat.com/browse/THREESCALE-8301
When a tenant is created declaratively, using the TenantCR, and afterwards it’s deleted from the 3scale admin portal UI, the operator starts creating tenants in an infinite loop.
The issue was caused by a wrong reconciliation logic that did not take into account the NOT FOUND response when reading an admin user. That returned an error, which turned up into a new reconciliation loop before the tenantID and AdminID was stored in the status section. Every new reconciliation loop ended up creatiing a new tenant.
The reconciliation loop logic has been refactored. Basically:
* Read tenant from status.TenantId
* If not found, create it and store in status new tenant ID together with 0 in the status.AdminId
* Read tenant user list …
> fix tenant reconciliation

- controllers/capabilities/activedoc_threescale_reconciler.go
- controllers/capabilities/backend_controller.go
- controllers/capabilities/openapi_backend_reconciler.go
- controllers/capabilities/openapi_controller.go
- controllers/capabilities/openapi_product_reconciler.go
- doc/operator-application-capabilities.md
- go.mod
- go.sum
- pkg/controller/helper/shared.go
- pkg/helper/openapi_utils.go
Jira issue: https://issues.redhat.com/browse/THREESCALE-8287
The operator crashes when the activedoc's OpenAPI has `Components.Schemas[]` fields.
Internally, the operator tries to compare and the comparator library (`github.com/google/go-cmp/cmp`) was panic-ing  because it was trying to compare unexported field. 
The fix has been configure the comparator to ignore unexported fields from that structure.
Additionally, the openapi3 library has been upgraded from v0.22.0 -> v0.94.0
Create OpenAPI doc file (o.yaml):
```yaml
---
openapi: "3.0.0"
info:
title: "some title"
description: "some description"
version: "1.0.0"
paths:
/pet:
get:
operationId: "getPet"
responses:
405:
description: "invalid input"
content: {}
components:
schemas:
ApiResponse:
type: object
properties:
code:
type: integer …
```
> fix operator crash when creating activedoc with components section

- apis/apps/v1alpha1/apimanager_types.go
- pkg/3scale/amp/operator/upgrade.go
Fix `func (apimanager *APIManager) IsSystemMysqlEnabled() bool`. System mysql pod template labels were not upgraded
Deploy 3scale 2.11 with system mysql. System mysql pod labels are:
```yaml
$ oc get "$(oc get pods --selector deploymentconfig=system-mysql -o name)" -o jsonpath='{.metadata.labels}' | yq e -P
app: 3scale-api-management
com.redhat.component-name: system-mysql
com.redhat.component-type: application
com.redhat.component-version: "57"
com.redhat.product-name: 3scale
com.redhat.product-version: "2.11"
deployment: system-mysql-1
deploymentConfig: system-mysql
deploymentconfig: system-mysql
threescale_component: system
threescale_component_element: mysql
```
Run upgrade to 2.12 procedure. For this step, I just removed the operator and `make run` the version from this PR branch. …
> fix system mysql pod label upgrade

- controllers/capabilities/tenant_controller.go
reqLogger.Info was causing a panic which could cause the operator to crash in some scenarios. Added extra field to prevent it from panicking.
1. Create a tenant  through CR
2. Delete tenant through ui
3. Delete tenant CR
4. Operator shouldn't panic and crash
> Fix reqlogger panic that caused operator to crash

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/apps/apimanager_controller.go
The 3scale operator role assigned to the service account running the 3scale operator pod missed permission to `get`, `list` `clusterversions.config.openshift.io`. It was complaining with the following error:
```
E0505 12:54:28.484088       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1.ClusterVersion: clusterversions.config.openshift.io is forbidden: User "system:serviceaccount:eguzki:3scale-operator" cannot list resource "clusterversions" in API group "config.openshift.io" at the cluster scope
```
Deploy the 3scale operator from OLM: follow our [user guide to deploy using OLM](https://github.com/3scale/3scale-operator/blob/master/doc/development.md#deploy-custom-3scale-operator-using-olm)
Create APIManager object, check all 3scale …
> grant clusterversions.config.openshift.io resource add and list verbs

- controllers/capabilities/developeraccount_controller.go
- doc/developeraccount-reference.md
Delete developer account when cr is deleted
* Install CRDs and run 3scale operator
```
make install
oc new-project 3scale
make run
```
* Create S3 secret for APIManager
```
---
apiVersion: v1
kind: Secret
metadata:
name: aws-auth
stringData:
type: Opaque
EOF
```
* Create `APIManager`
```
oc apply -f - <<EOF                                                             
---             
metadata:
spec:
wildcardDomain: apps.some-valid-domain
system:
fileStorage:
name: aws-auth
EOF
```
* …
> THREESCALE-7052 - feat: delete developer account

- controllers/capabilities/developeruser_controller.go
- doc/developeruser-reference.md
- pkg/controller/helper/shared.go
Delete developer user when cr is deleted
* Install CRDs and run 3scale operator
```
make install
oc new-project 3scale
make run
```
* Create S3 secret for APIManager
```
---
apiVersion: v1
kind: Secret
metadata:
name: aws-auth
stringData:
type: Opaque
EOF
```
* Create `APIManager`
```
oc apply -f - <<EOF                                                             
---             
metadata:
spec:
wildcardDomain: apps.some-valid-domain
system:
fileStorage:
name: aws-auth
EOF
```
* Create …
> THREESCALE-7055 - feat: delete developer user

- apis/apps/v1alpha1/apimanager_types.go
- bundle/manifests/apps.3scale.net_apimanagers.yaml
- config/crd/bases/apps.3scale.net_apimanagers.yaml
Fixes: https://issues.redhat.com/browse/THREESCALE-8445
In summary, installing one old version (2.11) operator makes OLM to replace CRD to the old version. This scenario only applies to namespaced operators. In cluster wide operators cannot happen because the OLM upgrade path does not allow. It would be necessary to uninstall and install again.  
This is mainly because the CRD of APIManager keeps the same version even if there are new fields.
The fix is about making the CRD 2.11 to preserve unknown fields, so even 2.11 CRD is installed, already stored fields from 2.12 will be available.
* Install CRD from 2.12 
```
git checkout 3scale-2.12-stable
k apply -f bundle/manifests/apps.3scale.net_apimanagers.yaml
``` 
* Create APImanager 2.12 with `spec.externalComponents`
```yaml
k apply -f - …
```
> Apimanager 2.11: add preserve unknown fields

- pkg/3scale/amp/component/highavailability_options.go
- pkg/3scale/amp/operator/highavailability_options_provider.go
The `GetHighAvailabilityOptions` method that is used by all external component reconcilers has logic that expects the secrets for all the components being external. This means that even when a dependency is configured as internal, as long as another dependency is configured external this logic will try to retrieve the secret for the internal dependency, failing the reconciliation.
Fix this by making the logic only populate the options for the dependencies configured as external.
Fixes https://issues.redhat.com/browse/THREESCALE-8467
> THREESCALE-8467 (1): Granular options provider logic

- pkg/3scale/amp/component/redis.go
- pkg/3scale/amp/operator/redis_reconciler.go
- pkg/3scale/amp/template/adapters/redis.go
Currently, the Backend Redis reconciler creates a `redis-config` ConfigMap that is used by the deployments, but the System Redis also depends on that ConfigMap. This results in the failure to deploy the System Redis when the Backend Redis is configured as external (which is now possible since making this configuration fine grained).
Fix this by making the ConfigMap reconciliation common among both Redis reconcilers, which will result in the ConfigMap being created regardless of what combination of internal/external Redis is configured.
Fixes https://issues.redhat.com/browse/THREESCALE-8467
> THREESCALE-8467 (2): Make Redis ConfigMap common

- pkg/3scale/amp/component/highavailability_options.go
- pkg/3scale/amp/component/redis.go
- pkg/3scale/amp/operator/highavailability_options_provider.go
- pkg/3scale/amp/operator/redis_reconciler.go
- pkg/3scale/amp/template/adapters/redis.go
Fixes https://issues.redhat.com/browse/THREESCALE-8467
> [backport] fix granular databases

- pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml
- pkg/3scale/amp/auto-generated-templates/amp/amp.yml
- pkg/3scale/amp/component/system.go
Jira Issue: https://issues.redhat.com/browse/THREESCALE-8491
Rails 5.2 fails not only the web server but also other tasks
when secret_key_base is not present. Adding a dummy value here
to workaround that.
Also usage of DELTA_INDEX_INTERVAL and FULL_REINDEX_INTERVAL
was removed in 3scale/porta@4b01db2
See rails/rails#32947
> add secret_key_base to system sphinx

- .circleci/config.yml
Unittest memory footpring increased up to 7.5 GB and requires large resource class. 
https://github.com/3scale/3scale-operator/pull/742#issuecomment-1160226259
Opened issue to try to fix the memory footpring: https://issues.redhat.com/browse/THREESCALE-8493
> fix circleci tests

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- pkg/3scale/amp/component/images.go
- pkg/restore/apimanager_restore.go
Fixes https://issues.redhat.com/browse/THREESCALE-8476
Downstream version of the operator is using `registry.redhat.io/openshift4/ose-cli:v4.7`. In this version, the command line `oc exec ${podname} bash -- -c "bundle exec rake zync:resync:domains"` fails. Indeed, the command line syntax is not correct. It has been working until now because the upstream version of the cli was `quay.io/openshift/origin-cli:4.2` shipping `oc` version 4.2. For this version, the above command line just **works**, But, it shouldn't. And it was fixed. In `oc` 4.7, as expected, it does not work. 
So this PR, fixes the command line and upgrades the image containing `oc` to 4.7
Those defined in https://github.com/3scale/3scale-operator/pull/758
> THREESCALE-8476 fix domain resync command line

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/capabilities/developeraccount_controller.go
- controllers/capabilities/developeruser_controller.go
Missing finalizer permissions for developer user and developer account for an OLM install. 
The following developer user reconcile error happens due to missing permissions
```
{"level":"error","ts":1658829782.950092,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"capabilities.3scale.net","reconcilerKind":"DeveloperUser","controller":"developeruser","name":"hsdg6wfltms","namespace":"3scale-alpha-190","error":"developerusers.capabilities.3scale.net \"hsdg6wfltms\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/remote-source/deps/gomod/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controlle …
```
> THREESCALE-7055 - fix: add finalizer permissions for developer user and developer account

- controllers/capabilities/proxyconfigpromote_controller.go
- doc/proxyConfigPromote-reference.md
Addressing issues raised in this [comment ](https://issues.redhat.com/browse/THREESCALE-7135)
1. Deploy 3scale-operator locally 
2.Create dummy smtp secret
```sh
---
kind: Secret
apiVersion: v1
metadata: 
data: 
type: Opaque
EOF
```
3.Create apimanager resource
```sh
---
metadata: 
spec: 
system: 
fileStorage: 
simpleStorageService: 
configurationSecretRef: 
wildcardDomain: <cluster_domain>
EOF
```
cluster domain example : …
> Adressing proxy promotion issues

- controllers/capabilities/proxyconfigpromote_controller.go
update the status in ProxyConfigPromote if the Product is not found
1. Deploy 3scale-operator locally
2. Create dummy smtp secret
```bash
---
kind: Secret
apiVersion: v1
metadata: 
data: 
type: Opaque
EOF
```
3.Create apimanager resource
```bash
---
metadata: 
spec: 
system: 
fileStorage: 
simpleStorageService: 
configurationSecretRef: 
wildcardDomain: <cluster_domain>
EOF
```
4. As no products exist create proxyconfigpromote resource to promote …
> Update the ProxyConfigPromote status when the product not found

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- pkg/3scale/amp/product/3scale_release.go
Master will include target release version, like https://github.com/3scale/3scale-operator/blob/master/version/version.go
> bump version 2.13

- doc/apimanager-reference.md
- doc/apimanagerbackup-reference.md
- doc/apimanagerrestore-reference.md
The documentation makes references to the kubernetes API docs, https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17
This site is not opened by the latest version of Chrome due to being insecure, and nothing is found there anyway.
This PR updates all of the links to use the latest Kubernetes reference.
> Update links to k8s API reference

- pkg/3scale/amp/operator/system_reconciler.go
- pkg/3scale/amp/upgrade/sphinx-deployment-secret-key-base.go
Completes https://issues.redhat.com/browse/THREESCALE-8491 after #762 
Adding env var mutator to the sphinx deployment resource to 
* SECRET_KEY_BASE added 
* DELTA_INDEX_INTERVAL removed
* FULL_REINDEX_INTERVAL removed
Deploy 2.12
```
git checkout 3scale-2.12.0-GA
```
```
make run
```
```yaml
k apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
name: aws-auth
stringData:
AWS_ACCESS_KEY_ID: testID
AWS_SECRET_ACCESS_KEY: testkey
AWS_BUCKET: testbucket
type: Opaque
EOF
```
```yaml
k apply -f - <<EOF
---
metadata:
spec:
wildcardDomain: eguzki.apps.dev-eng-ocp4-operator.dev.3sca.net
system:
fileStorage: …
```
> THREESCALE-8491 upgrade system sphinx secret key env var

- apis/apps/v1alpha1/apimanager_types.go
- apis/apps/v1alpha1/apimanager_types_test.go
- doc/apimanager-reference.md
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/system_options.go
- pkg/3scale/amp/operator/apicast_options_provider.go
- pkg/3scale/amp/operator/apicast_reconciler.go
- pkg/3scale/amp/operator/apicast_reconciler_test.go
- pkg/3scale/amp/operator/backend_options_provider.go
- pkg/3scale/amp/operator/backend_reconciler.go
- pkg/3scale/amp/operator/backend_reconciler_test.go
- pkg/3scale/amp/operator/system_options_provider.go
- pkg/3scale/amp/operator/system_options_provider_test.go
- pkg/3scale/amp/operator/system_reconciler.go
- pkg/3scale/amp/operator/system_reconciler_test.go
- pkg/3scale/amp/operator/zync_options_provider.go
- pkg/3scale/amp/operator/zync_reconciler.go
- pkg/3scale/amp/operator/zync_reconciler_test.go
- pkg/3scale/amp/prometheusrules/system_app_rules.go
- pkg/reconcilers/deploymentconfig.go
- test/unitcontrollers/apimanager_controller_test.go
Implements https://issues.redhat.com/browse/THREESCALE-8754
* Remove adding replica values to the CR
* Reconciliation (implemented by the mutator) only added when the `replicas` field is set
Components
run env
```
make install
make run
```
Deploy APIManager CR with no replica definition
```yaml
k apply -f -<<EOF
---
apiVersion: v1
kind: Secret
metadata:
name: aws-auth
stringData:
AWS_ACCESS_KEY_ID: somekey
AWS_BUCKET: example.com
type: Opaque
---
metadata:
spec:
wildcardDomain: example.com
system:
fileStorage:
name: aws-auth
EOF
```
Check that the APIManager …
> THREESCALE-8754 Enhance replica reconciliation

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/rbac/leader_election_role.yaml
New RBAC permissions are needed by default for leaderelection for the `coordination/v1` API
The PR https://github.com/3scale/3scale-operator/pull/785 upgraded controller-runtime from 0.6 to 0.12. However, the controller runtime's v0.7.0 added a change  leaderlock from ConfigMap to ConfigMapsLeasesResourceLock. From [changelog](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.7.0)
```
Change leaderlock from ConfigMap to ConfigMapsLeasesResourceLock (https://github.com/kubernetes-sigs/controller-runtime/pull/1144)
Impact: New RBAC permissions are needed by default for leaderelection (for
the coordination/v1 API). The new lock will automatically deal with
existing configmap locks (e.g. during upgrades). The can be set to its
previous value ("configmaps") in …
```
> RBAC permissions for the `coordination/v1` API

- doc/apimanager-reference.md
The table is not rendered due to invalid number of cells in separator row.
> Fix StsSpec table rendering

- pkg/3scale/amp/operator/apicast_reconciler.go
New fields were added to the APIManager CRD to reconcile the APICAST_SERVICE_CACHE_SIZE environment variable in the Apicast containers. However, it missed the logic to reconcile updates to the CR.
Add the mutator that sets the environment variable in the case of updates.
On a cluster, run the operator and create an APIManager with the new fields set. Check that once reconciled the `DeploymentConfigs` include the environment variable with the value from the new fields:
1. Apply the manifests
```sh
make install
``` 
2. Run the operator
```sh
make run
```
3. Create an APIManager that includes the following in the spec:
```yaml
apicast:
productionSpec:
serviceCacheSize: 20
stagingSpec:
serviceCacheSize: 10
```
4. Check the DeploymentConfigs for APICast
```sh
oc get dc/apicast-staging -o yaml …
```
> THREESCALE-8963: Reconcile updates to APICAST_SERVICE_CACHE_SIZE

- go.mod
- go.sum
Fixes: https://issues.redhat.com/browse/THREESCALE-9476 `3scale Backend Operator capability does not allow creating more than 500 Backends`
Fixes: https://issues.redhat.com/browse/THREESCALE-8572 `3scale Backend Operator capability does not allow creating more than 500 methods`
* Run the operator in the current branch
```
make run
```
* Deploy 3scale
```yaml
k apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
name: aws-auth
stringData:
AWS_ACCESS_KEY_ID: testID
AWS_SECRET_ACCESS_KEY: testkey
AWS_BUCKET: testbucket
type: Opaque
EOF
```
```yaml
k apply -f - <<EOF
---
metadata:
spec:
wildcardDomain: example.net
system:
fileStorage: …
```
> THREESCALE-9476 create more than 500 backends

- controllers/apps/apimanagerbackup_logic_reconciler.go
- go.mod
- pkg/common/status_conditions.go
[MGDAPI-5152](https://issues.redhat.com/browse/MGDAPI-5152)
As part of the changes for the above ticket for openshift v4.13 support I was unable to resolve dep conflicts in 3scale-operator without removing use of the deprecated clock package. I've swapped the two uses for the newer version in this PR.
> MGDAPI-5152 - replace deprecated clock package usage

- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/operator/system_reconciler.go
- pkg/helper/envvarutils.go
- pkg/reconcilers/deploymentconfig.go
- pkg/reconcilers/deploymentconfig_test.go
`FILE_UPLOAD_STORAGE` env var is added as part of the config map, and added separately after resulting in duplicate env vars on some DeploymentConfigs.
On v4.11 when updating any of the deployment configs a new replication controller is created and there are warnings about a duplicate `FILE_UPLOAD_STORAGE` env var in the deploy logs. However on v4.13 these no longer show as warnings but as errors and the rollout is marked as failed. This duplicate env var is present as it is added from the base config map and then appended again.
*v4.11*
```
--> pre: Running hook pod ...
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /opt/deps/rubygems/github.com/3scale/prawn/prawn-external-gitcommit- …
```
> MGDAPI-5152 - remove duplicate FILE_UPLOAD_STORAGE env var

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
Fixes missing env in the CSV that should have been added in #818
> add RELATED_IMAGE_SYSTEM_SEARCHD to the CSV

- CHANGELOG.md
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/system_options.go
- pkg/3scale/amp/operator/system_options_provider.go
- pkg/3scale/amp/operator/system_options_provider_test.go
- pkg/3scale/amp/prometheusrules/system_app_rules.go
- pkg/assets/bindata.go
- pkg/upgrade/upgrade_system_backend_urls_2.14.go
Related to https://github.com/3scale/porta/pull/3324
The description about different Backend URLs that are used in the System component are provided in the [porta PR description](https://github.com/3scale/porta/pull/3324).
This PR removes the `BACKEND_ROUTE` environment variable, whose value is now `http://backend-listener:3000/internal/` - which is confusing because "route" kind of suggests that it would be the value of the backend OCP route.
* Deleted `system-app` env var `APICAST_BACKEND_ROOT_ENDPOINT`
* Deleted `system-app` env var `BACKEND_ROUTE`
* Add `system-app` env var `BACKEND_URL`:  `service_endpoint` value from `backend-listener` secret (i.e. `http://backend-listener:3000`). Note `/internal` is no longer provided. That will be added by System.
* Add `system-app` env var …
> THREESCALE-9558: Separate env vars for Core API and public route

- pkg/3scale/amp/component/system_searchd.go
- pkg/3scale/amp/operator/system_searchd_reconciler.go
- pkg/reconcilers/deploymentconfig.go
Fixes https://issues.redhat.com/browse/THREESCALE-9710
The searchd deployment had [Rolling](https://docs.openshift.com/container-platform/3.11/dev_guide/deployments/deployment_strategies.html#rolling-strategy) and a PVC with RWO access mode. Thus, on rolling, the new pod would never be fully deployed because the PV was attached to the old pod. And the old pod would never release the PVC until the new pod was up and running. A deadlock situation. 
The fix is to use the [Recreate Strategy](https://docs.openshift.com/container-platform/3.11/dev_guide/deployments/deployment_strategies.html#recreate-strategy). Same strategy that other 3scale component deployments have when PVCs with RWO access mode is required. For example, mysql, postgresql or redis. Databases.
* Requires openshift (oc CLI) …
> THREESCALE-9710 searchd deployment strategy: recreate

- doc/prometheusrules/apicast.yaml
- pkg/3scale/amp/component/apicast_monitoring.go
* fixes https://github.com/3scale/3scale-operator/issues/838
> fix #838 - removed unnecessary comma

- Makefile
make command bundle-custom-build failing on the sed command e.g.
```bash
make bundle-custom-build IMG=quay.io/austincunningham/3scale-operator:0.0.1 BUNDLE_IMG=quay.io/austincunningham/3scale-operator-bundles:0.0.1
Update metadata to avoid collision with existing 3scale Operator official public operators catalog entries
using BUNDLE_PREFIX dev1689318844
/home/austincunningham/repo-integr8ly/3scale-operator/bin/yq --inplace '.metadata.name = "dev1689318844-3scale-operator.0.0.1"' /home/austincunningham/repo-integr8ly/3scale-operator/bundle/manifests/3scale-operator.clusterserviceversion.yaml
/home/austincunningham/repo-integr8ly/3scale-operator/bin/yq --inplace '.spec.displayName = "dev1689318844 3scale operator"' /home/austincunningham/repo-integr8ly/3scale-operator/bundle/manifests/3scale …
```
> fix bundle-custom-update

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- pkg/3scale/amp/component/images.go
- pkg/3scale/amp/component/redis.go
- pkg/3scale/amp/operator/redis_reconciler.go
- pkg/upgrade/common.go
- pkg/upgrade/redis_2.14.go
Support Redis 6 for internal databases. System and Backend redis are upgraded to Redis 6
Fixes https://issues.redhat.com/browse/THREESCALE-9564
The upgrade should only happen when redis is used as internal database, either for backend or system. 
From the  [Redis 6 release notes](https://raw.githubusercontent.com/antirez/redis/6.0/00-RELEASENOTES)
```
Migrating from 5.0 to 6.0
=========================
Redis 6.0 is mostly a strict superset of 5.0, you should not have any problem
upgrading your application from 5.0 to 6.0. However this is a list of small
non-backward compatible changes introduced in the 6.0 release:
* The SPOP <count> command no longer returns null when the set key does not
exist. Now it returns the empty set as it should and as happens when it is
called with a 0 argument. …
```
> THREESCALE-9564 redis 6

- .circleci/config.yml
- Dockerfile
- doc/development.md
- go.mod
- pkg/assets/bindata.go
Fixes https://issues.redhat.com/browse/THREESCALE-9984
> THREESCALE-9984: go1.19

- pkg/3scale/amp/component/backend.go
- pkg/reconcilers/deploymentconfig.go
[THREESCALE-7864](https://issues.redhat.com//browse/THREESCALE-7864)
set async by default on backend work
- Create a project `oc new-project 3scale-test`
- `make install`
- `make run`
- Create a s3 secret
```bash
---
kind: Secret
apiVersion: v1
metadata:
data:
type: Opaque
EOF
```
- Create an apimanager CR using that secret e.g.
```bash
---
metadata:
spec:
system:
fileStorage:
wildcardDomain: apps.aucunnin.wx3t.s1.devshift.org
EOF
```
- Check …
> THREESCALE-7864 set async by default on backend work

- controllers/capabilities/tenant_controller.go
- controllers/capabilities/tenant_internal_reconciler.go
Jira: https://issues.redhat.com/browse/THREESCALE-8497
Added logic to support restoration from tenant CR when the tenant already exists in the database.
- OCP/OSD cluster
1. Create namespace
```
```
2. Apply CRDs
```
make install
```
3. Create dummy secret
```
---
apiVersion: v1
kind: Secret
metadata:
stringData:
type: Opaque
EOF
```
4. Create APIM (update wildcard domain)
```
oc create -f - << EOF
metadata:
namespace: threescale
spec:
system: 
fileStorage: 
simpleStorageService: 
configurationSecretRef: 
name: …
```
> Tenant Duplication when restoring Databases

- controllers/capabilities/activedoc_controller.go
- controllers/capabilities/application_controller.go
- controllers/capabilities/backend_controller.go
- controllers/capabilities/custompolicydefinition_controller.go
- controllers/capabilities/developeraccount_controller.go
- controllers/capabilities/developeruser_controller.go
- controllers/capabilities/product_controller.go
- controllers/capabilities/proxyconfigpromote_controller.go
- controllers/capabilities/tenant_controller.go
- doc/development.md
- doc/operator-user-guide.md
- pkg/controller/helper/threescale_api.go
- pkg/controller/helper/threescale_api_test.go
[THREESCALE-7836](https://issues.redhat.com/browse/THREESCALE-7836)
This refactors the insecure skip verify logic for the porta client to be enabled via annotations on individual CRs rather than globally as an environment variable.
This PR also add documentation around supported environment variables.
> THREESCALE-7836 Refactor TLS InsecureSkipVerify logic to use annotations

- apis/capabilities/v1beta1/proxyconfigpromote_types.go
- controllers/capabilities/application_controller_test.go
- controllers/capabilities/application_status_reconciler_test.go
- controllers/capabilities/applications_test.go
- controllers/capabilities/proxyconfigpromote_controller.go
- controllers/capabilities/proxyconfigpromote_controller_test.go
- controllers/capabilities/proxyconfigpromote_status_reconciler.go
- controllers/capabilities/proxyconfigpromote_status_reconciler_test.go
**What**
Slight refactor to proxyConfigPromote so that the status is updated even if there's an error of updating to production if there's no actual updates to be done. Jira: https://issues.redhat.com/browse/THREESCALE-10092
NOTE: Some unit tests have been slightly refactored - there's more refactors to unit tests to be done in future Jiras, for example, configuring mock client that could be used within different tests instead of relying on proxyPromote tests etc.
**To Verify**
From this branch run:
- Create project
```
```
- Create dummy secret
```
---
kind: Secret
apiVersion: v1
metadata: 
namespace: threescale
data: …
```
> THREESCALE-10092 refactor status reporting on proxyConfigPromote

- apis/capabilities/v1beta1/backend_types.go
- apis/capabilities/v1beta1/product_types.go
- pkg/helper/openapi_utils.go
Jira: https://issues.redhat.com/browse/THREESCALE-8128
Removed the toLower when making validation of backend and product spec. Few years ago 3scale api did not support the camelCase system name, it does now. 
From this branch:
- run to create new project
```
```
- run to install CRDs
```
make install
```
- create dummy secret
```
---
apiVersion: v1
kind: Secret
metadata:
stringData:
type: Opaque
EOF
```
- fetch cluster domain
```
```
- create apim
``` …
```
> THREESCALE-8128 remove unnecesary camel case removal

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/manifests/bases/3scale-operator.clusterserviceversion.yaml
Adding maxOpenshiftVersion to 3scale operator 2.13 stable.
> add 4.13 as maxOpenshift version to threescale 2.13

- controllers/capabilities/openapi_backend_reconciler.go
- controllers/capabilities/openapi_controller.go
- controllers/capabilities/openapi_product_reconciler.go
- controllers/capabilities/tenant_internal_reconciler.go
- pkg/3scale/amp/operator/base_apimanager_logic_reconciler.go
- pkg/reconcilers/base_reconciler.go
Jira: https://issues.redhat.com/browse/THREESCALE-10137
- Create new project
```
```
- Install CRDs
```
make install
```
- Run the operator
```
make run
```
- Create new secret to be consumed by APIM
```
---
apiVersion: v1
kind: Secret
metadata:
stringData:
type: Opaque
EOF
```
- Fetch cluster domain
```
```
- Create APIM
```
kubectl apply -f - <<EOF                                                        
---
kind: …
```
> THREESCALE-10137 add owner ref to openapi

- controllers/capabilities/openapi_backend_reconciler.go
- controllers/capabilities/openapi_product_reconciler.go
- doc/openapi-reference.md
- doc/operator-user-guide.md
Jira: https://issues.redhat.com/browse/THREESCALE-10162
- Create new project
```
```
- Install CRDs
```
make install
```
- Run the operator
```
make run
```
- Create new secret to be consumed by APIM
```
---
apiVersion: v1
kind: Secret
metadata:
stringData:
type: Opaque
EOF
```
- Fetch cluster domain
```
```
- Create APIM
```
kubectl apply -f - <<EOF                                                        
---
kind: …
```
> THREESCALE-10162 add skip insecure verify to OpenAPI backend and product

- controllers/capabilities/proxyconfigpromote_controller.go
Follow up from https://github.com/3scale/3scale-operator/pull/863
Verification:
Follow steps from the previous PR as follow up.
Add another case where the proxyConfigPromote created only promotes to stage but with production set to false.
Example:
```
spec:
productCRName: product1
production: false
deleteCR: false
```
> THREESCALE-10092 fix promote to stage with false production value

- doc/prometheusrules/apicast.yaml
- pkg/3scale/amp/component/apicast_monitoring.go
- pkg/3scale/amp/operator/apicast_reconciler.go
- pkg/reconcilers/base_reconciler.go
- pkg/reconcilers/prometheus_rules.go
- pkg/reconcilers/prometheus_rules_test.go
Jira: https://issues.redhat.com/browse/THREESCALE-10098
The rule 'ThreescaleApicastRequestTime' will be removed in the next 3scale release.
- `checkout this branch`
- provision a cluster
when cluster is ready:
- set up 3scale operator locally, https://github.com/3scale/3scale-operator/blob/master/doc/development.md#run-3scale-operator-locally but don't  `make run` the operator yet.
- create a new `secret` resource
-  add an API Manager CR. In the spec, ensure to enable monitoring like so:
```
monitoring:
enablePrometheusRules: true
enabled: true
```
- now `make run` to start the operator
- open the `PrometheusRule` CRs & in the `apicast` YAML verify that the 'ThreescaleApicastRequestTime' rule does not exist.
- at this stage `stop` the operator
- go back into `apicast` and create your own …
> THREESCALE-10098 Remove Prometheus Rule 'ThreescaleApicastRequestTime'

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/manifests/bases/3scale-operator.clusterserviceversion.yaml
JIRA: [THREESCALE-10387](https://issues.redhat.com/browse/THREESCALE-10387)
Adding 4.14 as maxOpenShiftVersion to 3scale-operator 2.14 stable.
> THREESCALE-10387 add 4.14 as maxOpenShiftVersion to threescale 2.14

- pkg/3scale/amp/component/backend.go
- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/component/system_searchd.go
- pkg/3scale/amp/operator/system_reconciler.go
- pkg/3scale/amp/operator/system_searchd_reconciler.go
- pkg/reconcilers/deploymentconfig.go
- pkg/reconcilers/deploymentconfig_test.go
Jira: https://issues.redhat.com/browse/THREESCALE-9556
Probes are required in the following DeploymentConfigs:  
- `backend-cron` Liveness probe  
- `backend-worker` Liveness probe  
- `system-sidekiq` Liveness probe  
- `system-searchd` Readiness probe
- Provision a cluster.
- Once ready, log in to your cluster via CLI.
- Checkout master branch (ensure its up to date with upstream):
```
git checkout master
```
- Installs CRDs:
```
make install
```
- Create a new project:
```
oc new-project 3scale-test
```
- Create a new secret:
```
kind: Secret
apiVersion: v1
metadata:
data:
type: Opaque …
```
> THREESCALE-9556 Add liveness/readyness probes to pods

- controllers/apps/apimanager_controller.go
- controllers/apps/apimanager_status_reconciler.go
- pkg/3scale/amp/component/apicast.go
- pkg/3scale/amp/operator/apicast_options_provider.go
- pkg/3scale/amp/operator/apicast_options_provider_test.go
- pkg/3scale/amp/operator/apicast_reconciler.go
- pkg/3scale/amp/operator/apicast_reconciler_test.go
- pkg/3scale/amp/operator/base_apimanager_logic_reconciler.go
- pkg/helper/deployment.go
- pkg/reconcilers/deployment.go
- pkg/reconcilers/deployment_test.go
- pkg/reconcilers/service.go
- pkg/upgrade/migrate_deployment_config_2.15.go
JIRA: [THREESCALE-10388](https://issues.redhat.com/browse/THREESCALE-10388)
This is the first PR against the new feature branch `threescale-10163` that will be used while implementing the changes needed to migrate each of 3scale-operator's DeploymentConfigs to Deployments - see [epic](https://issues.redhat.com/browse/THREESCALE-10163).
This PR replaces the `apicast-staging` and `apicast-production` DeploymentConfigs with Deployments. The PR also provides the upgrade scaffolding that will be used by the remaining DeploymentConfigs.
1. Provision a cluster
2. Install 3scale locally using master
3. Checkout this PR
4. Re-run 3scale locally
5. Verify that the new `apicast-staging` and `apicast-production` Deployments are created
6. Verify that the `apicast-staging` and `apicast-production` …
> THREESCALE-10388 Migrate apicast DeploymentConfigs to Deployments

- pkg/3scale/amp/component/memcached.go
- pkg/3scale/amp/operator/memcached_options_provider.go
- pkg/3scale/amp/operator/memcached_options_provider_test.go
- pkg/3scale/amp/operator/memcached_reconciler.go
- pkg/3scale/amp/operator/memcached_reconciler_test.go
JIRA: [THREESCALE-10390](https://issues.redhat.com/browse/THREESCALE-10390)
This PR replaces the `system-memcache` DeploymentConfig with a Deployment.
1. Provision a cluster
2. Install 3scale locally using master
3. Checkout this PR
4. Re-run 3scale locally
5. Verify that the new `system-memcache` Deployment is created
6. Verify that the `system-memcache` DeploymentConfig is deleted once the Deployment reports healthy
> THREESCALE-10390 Migrate memcache DeploymentConfig to Deployment

- controllers/capabilities/openapi_controller.go
Jira: https://issues.redhat.com/browse/THREESCALE-10519
This is a minor fix for OIDC PR https://github.com/3scale/3scale-operator/pull/837
**Before** -   if OpenAPI CR contains oidc section , but OAS (swagger produc source file) is without security section - Info message appear in Operator log, as implemented here:
https://github.com/3scale/3scale-operator/blob/master/controllers/capabilities/openapi_controller.go#L403-L406
Fix: add 
**Now** - added warning to Openapi CR, as in log below:
```
$ oc describe openapis openapi-example 
Name:         openapi-example
Namespace:    3scale-test
Labels:       <none>
Annotations:  <none>
API Version:  capabilities.3scale.net/v1beta1
Kind:         OpenAPI
Metadata:
Creation Timestamp:  2023-11-29T10:57:00Z
Generation:          1
Managed Fields:
API …
```
> THREESCALE-10519 - OAS without security section, while OpenAPI CR contains oidc section

- controllers/capabilities/mapping_rules.go
- controllers/capabilities/openapi_controller.go
- controllers/capabilities/proxy.go
- doc/openapi-user-guide.md
Jira: https://issues.redhat.com/browse/THREESCALE-10646
**- PR created instead of original PR/branch https://github.com/3scale/3scale-operator/pull/903, that was closed. Please see Review comments in PR 903**
- This task is related to Bug https://issues.redhat.com/browse/THREESCALE-10238 - The Operator reconciles a Product created with the ProductCR when mapping rules are duplicated.  
Additional tasks related to [THREESCALE-10238](https://issues.redhat.com//browse/THREESCALE-10238) were opened, to investigate and fix issues found during curent development:
- Method added via UI is not saved, dissapered after rerun 3scale (make run). So Rules added via UI and using method that created via UI - dissapering after operator stop/start  - https://issues.redhat.com/browse/THREESCALE-10647
- …
> [WIP] THREESCALE-10646 - Product Mapping Rules reconciliation, metricMethod

- doc/monitoring-stack-deployment/3scale-scrape-configs.yaml
- doc/monitoring-stack-deployment/README.md
https://issues.redhat.com/browse/THREESCALE-10709
The steps for getting openshift monitoring data in the readme have been out of date for some time
You can no longer use basic auth to scrape data from openshift-monitoring see OCP docs for more information [here](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/monitoring/enabling-monitoring-for-user-defined-projects#accessing-metrics-from-outside-cluster_enabling-monitoring-for-user-defined-projects)
updated the 3scale-scrape-configs.yaml to use bearer token
added steps to the Readme to get the THANOS_QUERIER_BEARER_TOKEN
Provision a 3scale instance from this branch and follow the readme to test the monitoring stack installation.
> THREESCALE-10709 update monitoring stack deployment to use THANOS_QUERIER_BEARER_TOKEN

- pkg/3scale/amp/component/system_monitoring.go
`/yabeda-metrics` is being removed from System, only `/metrics` will remain: https://github.com/3scale/porta/pull/3680
> Do not fetch metrics from /yabeda-metrics on System

- pkg/3scale/amp/component/system.go
- pkg/3scale/amp/operator/apicast_reconciler_test.go
- pkg/3scale/amp/operator/backend_reconciler_test.go
- pkg/3scale/amp/operator/system_reconciler.go
- pkg/3scale/amp/operator/system_reconciler_test.go
- pkg/3scale/amp/operator/zync_reconciler_test.go
- pkg/helper/deployment.go
- pkg/helper/job.go
JIRA: [THREESCALE-10722](https://issues.redhat.com/browse/THREESCALE-10722)
This PR improves upon the existing PreHook and PostHook Jobs so that they are deleted and recreated whenever there is an image change.
1. Provision a cluster
2. Checkout this PR
3. Prepare to run the operator locally:
```bash
make install
make download
```
4. Create the Namespace, `s3-credentials` Secret, and the APIManager CR:
```bash
kind: Secret
apiVersion: v1
metadata:
data:
type: Opaque
EOF
apiVersion: …
```
> THREESCALE-10722 Refactored system-app Jobs to be recreated for each image change

- controllers/apps/apimanager_status_reconciler.go
JIRA: [THREESCALE-10754](https://issues.redhat.com/browse/THREESCALE-10754)
This fixes the APIManager status behavior so that it will continuously reconcile until it has the condition `Available=True`. This addresses some flaky behavior where the APIManager CR would never report as Available even though the installation was complete. 
Eye review and passing the PROW checks should be sufficient.
> THREESCALE-10754 Fix APIManager status to reconcile until Available

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/apps/apimanager_controller.go
Permissions missing for HPA branch when run as a container from an olm deployment
```
W0227 07:57:58.819129       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:3scale-test:3scale-operator" cannot list resource "horizontalpodautoscalers" in API group "autoscaling" in the namespace "3scale-test"
E0227 07:57:58.819149       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v2.HorizontalPodAutoscaler: failed to list *v2.HorizontalPodAutoscaler: horizontalpodautoscalers.autoscaling is forbidden: User "system:serviceaccount:3scale-test:3scale-operator" cannot list resource …
```
> THREESCALE-10713  add hpa rbac list and watch

- controllers/capabilities/methods.go
- doc/operator-application-capabilities.md
- pkg/helper/task_runner.go
Jira: https://issues.redhat.com/browse/THREESCALE-10792
<details>
- s3-creds-secret.yaml
```
kind: Secret
apiVersion: v1
metadata: 
data: 
AWS_ACCESS_KEY_ID: QUtJQVY2SVcccc
AWS_SECRET_ACCESS_KEY: aU5VbWdZY3hjSDFccc
AWS_BUCKET: dm1vY2NzZjZxOGxyZWRoYXRyaGccccc
AWS_REGION: ZXUtd2Vcccc
type: Opaque
```
- apimanagerCR.yaml
```
metadata:
name: example-apimanager
spec:
system: 
fileStorage: 
simpleStorageService: 
configurationSecretRef: 
wildcardDomain: apps.xxxxxx.axxxx.xxx.xxxxx.org
```
- backend.yml
```
apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
name: backend1
spec:
name: "Operated Backend 1"
systemName: "backend1"
description: "Operated Backend 1 …
```
> THREESCALE-10792 - fix - Method is used by the latest gateway configuration and cannot be deleted

- controllers/apps/apimanager_status_reconciler.go
- pkg/apispkg/common/status_conditions.go
**Description**
OpenTracing deprecation warning messages
**Jira**
https://issues.redhat.com/browse/THREESCALE-10771
**Verification**
**Installation**
- Create namespace
```
```
- Install CRDs
```
make install
```
- Run the operator
```
make run
```
- Create new secret to be consumed by APIM
```
---
apiVersion: v1
kind: Secret
metadata:
stringData:
type: Opaque
EOF
```
- Fetch cluster domain
```
```
- Create APIM
``` …
```
> THREESCALE-10771 add opentracing deprecation message

- controllers/apps/apimanager_controller.go
JIRA: [THREESCALE-10163](https://issues.redhat.com/browse/THREESCALE-10163)
This PR adds error handling to the ImageStream deletion which should have been included in #929
An eye review and passing the PR checks should be sufficient.
> THREESCALE-10163 Add error handling to ImageStream deletion

- controllers/apps/apimanager_controller.go
JIRA: [THREESCALE-10163](https://issues.redhat.com/browse/THREESCALE-10163)
This PR fixes the error handling during ImageStream deletion so it works when the operator is cluster scoped.
1. Provision a cluster and `oc login` to it
2. Checkout this PR
3. Run the e2e test and verify it passes
```bash
make test-e2e
```
> THREESCALE-10163 Fix ImageStream deletion error handling

- pkg/3scale/amp/component/system_searchd.go
- pkg/3scale/amp/operator/system_searchd_reconciler.go
JIRA: [THREESCALE-10835](https://issues.redhat.com/browse/THREESCALE-10835)
This PR adds the required code needed for the 3scale-operator to support the manticore version of system-searchd - the required steps are:
1. Delete the old `system-searchd` PVC (which is associated with the old `system-searchd` _DeploymentConfig_)
2. Create a new `system-searchd-manticore` PVC (which is used by the new `system-searchd` _Deployment_)
3. Once the `system-searchd` Deployment is running, create a one-off k8s Job that runs a reindexing command required by manticore
1. Provision a cluster and `oc` login to it
2. Checkout the `3scale-2.14-stable` branch
3. Run `go mod vendor && go mod tidy`
4. Prepare the cluster for a local install:
```bash
make install
make download
```
5. Create a Namespace and …
> THREESCALE-10835 Add support for manticore

- controllers/apps/apimanager_status_reconciler.go
- pkg/3scale/amp/operator/apicast_reconciler.go
- pkg/3scale/amp/operator/backend_reconciler.go
issue: [THREESCALE-10921](https://issues.redhat.com//browse/THREESCALE-10921)
Disable async mode if redis sentinels have authentication enabled
- install the operator without logical databases  following scripts will do this
[setup_db.sh](https://github.com/3scale-labs/3scale-perf-setup/blob/main/setup_db.sh)
[setup_apimanger.sh](https://github.com/3scale-labs/3scale-perf-setup/blob/main/setup_apimanager.sh)
- once finished remove hpa from apicast/productionspec, backend/listenerspec and backend/workerspec
- confirm no hpa set in 3scale-test namespace
```bash
oc get hpa --namespace 3scale-test
```
- scale down the operator deployment
-  we can mock a authenticated sentinel setup by editing the following secrets
- edit system-redis secret and add an @ symbol for `SENTINEL_HOSTS` 
- edit …
> THREESCALE-10921 disable async mode if sentinels require authentication

- pkg/3scale/amp/component/images.go
- pkg/helper/podHelper.go
Jira: https://issues.redhat.com/browse/THREESCALE-10937
Move the centos images to sclorg images since centos7 is no longer maintained.
Verification:
For MySQL and Redis e2e passing is enough
For PostgreSQL, pull the image locally to confirm it's available.
> THREESCALE-10937 update upstream db images

- pkg/3scale/amp/component/images.go
- pkg/helper/podHelper.go
Jira: https://issues.redhat.com/browse/THREESCALE-10937
centos streams 8 and 9 for Redis got removed.
Verification
E2e passing is sufficient
> THREESCALE-10937-2 update redis image

- pkg/upgrade/migrate_deployment_config_2.15.go
JIRA: [THREESCALE-10949](https://issues.redhat.com/browse/THREESCALE-10949)
This updates the DeploymentConfig to Deployment migration code to preserve the following custom, user-defined values:
* Deployment Labels
* Deployment Annotations
* Pod Labels
* Pod Annotations
* Container Environment Variables
* Volumes
* Volume Mounts
* Replicas
2. Prepare the cluster
```bash
make install
make download
```
3. Create the Namespace and `s3-credentials` Secret
```bash
kind: Secret
apiVersion: v1
metadata:
data:
type: Opaque …
```
> THREESCALE-10949 Preserve DC annotations, labels, and env vars

- controllers/apps/apimanager_controller.go
- doc/apimanager-reference.md
- doc/operator-user-guide.md
- pkg/3scale/amp/component/redis.go
- pkg/3scale/amp/component/redis_configmap_options.go
- pkg/3scale/amp/operator/redis_configmap_options_provider.go
- pkg/3scale/amp/operator/redis_options_provider.go
- pkg/3scale/amp/operator/redis_options_provider_test.go
- pkg/3scale/amp/operator/redis_reconciler.go
- pkg/reconcilers/configmap.go
Jira:  https://issues.redhat.com/browse/THREESCALE-9308
**This PR is recreated from https://github.com/3scale/3scale-operator/pull/954, that was closed because of significant changes in master**  
- Current PR is intended to prevent redis replication and slaves creation to prevent HeadCrab Vulnerability.
- for Internal Redis Only.
- If Redis is Internal than following records are added to configuration to disable replicaoff and slaveoff redis cli commands: 
rename-command REPLICAOF ""
rename-command SLAVEOF ""
- If both or one of these `rename-command` records removed or not found in `redis-config` config map - controller will restore them.
- PR does not prevent changes to other settings in the reids configuration (not REPLICAOF or SLAVEOF)
- s3-creds-secret.yaml
```
kind: Secret …
```
> THREESCALE 9308 HeadCrab Vulnerability (Redis)

- controllers/capabilities/application_status_reconciler.go
- controllers/capabilities/application_threescale_reconciler.go
[THREESCALE-10971](https://issues.redhat.com//browse/THREESCALE-10971)
Fix an intermittent nil pointer on application creation
Need to repeat a couple of times to verify
- Install this branch to the 3scale-test ns
- Install a product and application via cr you can use [./setup_product](https://github.com/3scale-labs/3scale-perf-setup/blob/main/setup_product.sh)
- confirm the operator doesn't crash
- you can use the script below to clean up the cluster before running a second time
```bash
#!/bin/bash
oc project 3scale-test
oc delete application application-cr --wait=false
oc delete product product1-cr --wait=false
oc delete backend backend1-cr --wait=false
oc delete developeruser developeruser01 --wait=false
oc delete developeraccount developeraccount01 --wait=false
sleep 60
oc delete …
```
> THREESCALE-10971 fix application creation nil pointer issue

- doc/apimanager-reference.md
JIRA: [THREESCALE-10670](https://issues.redhat.com/browse/THREESCALE-10670)
This PR updates the `system-sphinx` entry to instead be `system-searchd` for the Default APIManager components compute resources table. The actual [default resource values](https://github.com/3scale/3scale-operator/blob/ec722ac321dfdc0d9df883edcbd14719680c2dc0/pkg/3scale/amp/component/system_searchd_options.go#L40-L51) are unchanged so this just updates the name in the table.
Passing prow checks and eye review
> THREESCALE-10670 Update system-sphinx reference in docs to system-searchd

- controllers/apps/apimanager_status_reconciler.go
- doc/operator-user-guide.md
- pkg/3scale/amp/operator/backend_reconciler.go
- pkg/reconcilers/deployment.go
[THREESCALE-11117](https://issues.redhat.com//browse/THREESCALE-11117)
add a password check on redis uri in the backend to disable async if detected, 
improve url trim to handle all values
- install the operator locally
```bash
make install
---
metadata:
spec:
system:
fileStorage:
wildcardDomain: $DOMAIN
EOF
---
kind: Secret
apiVersion: v1
metadata:
data:
AWS_REGION: …
```
> THREESCALE-11117 add a password check on redis uri in the backend, improve url trim to handle all values

- controllers/capabilities/openapi_controller.go
- controllers/capabilities/openapi_controller_test.go
- controllers/capabilities/openapi_product_reconciler.go
- controllers/capabilities/openapi_product_reconciler_test.go
- doc/openapi-3scale-extensions.md
- doc/openapi-user-guide.md
- pkg/helper/openapi_utils.go
JIRA: [THREESCALE-11119](https://issues.redhat.com/browse/THREESCALE-11119)
This PR adds support for [OAS extensions](https://swagger.io/docs/specification/openapi-extensions/) as defined in the proposed [OpenAPI 3scale Extensions](https://github.com/carlkyrillos/3scale-operator/blob/THREESCALE-11119/doc/openapi-3scale-extensions.md) doc. The extensions allow users to define `ApplicationPlans`, `Policies`, `Metrics`, and more `MappingRule` fields in a Product CR created using OpenAPI.
2. Run the operator locally or via OLM using prebuilt image
```bash
BUNDLE_IMG=quay.io/ckyrillo/3scale-operator-bundles:threescale-11119 make bundle-run
```
3. Create a Namespace, dummy s3 Secret, and APIManager CR:
```bash
cat << EOF …
```
> THREESCALE-11119 OAS extension support for products

- controllers/apps/apimanager_controller.go
- controllers/apps/apimanager_status_reconciler.go
- pkg/helper/redis_database_version.go
- pkg/helper/system_database_versions.go
Jira: https://issues.redhat.com/browse/THREESCALE-11208
Added more logs + error reporting to APIM in case of failed preflights due to incorrectly configured/missing db secrets.
- Create namespace
```
```
- Install CRDs
```
make install
```
- Run the operator
```
make run
```
- Create new secret to be consumed by APIM
```
---
apiVersion: v1
kind: Secret
metadata:
stringData:
type: Opaque
EOF
```
- Fetch cluster domain
```
```
- Create APIM
```
kubectl …
```
> THREESCALE-11208 add logging to version checks

- apis/apps/v1alpha1/apimanager_types.go
- controllers/apps/apimanager_status_reconciler.go
- pkg/3scale/amp/operator/apicast_reconciler.go
- pkg/3scale/amp/operator/backend_reconciler.go
- pkg/3scale/amp/operator/base_apimanager_logic_reconciler.go
https://issues.redhat.com/browse/THREESCALE-11226
What
- removed the check of apicast hpa when sentinels are discovered
- added hpa removal once the async disabled flag is on
Verification
- install 3scale from this branch:
```
make install
---
metadata:
spec:
system:
fileStorage:
wildcardDomain: $DOMAIN
EOF
---
kind: Secret
apiVersion: v1
metadata:
data:
AWS_REGION: …
```
> THREESCALE-11226 extend hpa logic

- pkg/3scale/amp/component/zync.go
Jira: https://issues.redhat.com/browse/THREESCALE-11254
Verification:
Run upgrade from 2.14 to master and create a new tenant in 3scale. Confirm that the routes ownerRef is the deployment.
Run fresh install from this branch and create a new tenant in 3scale. Confirm that the routes ownerRef is the deployment.
> THREESCALE-11254 fix zync routes ownerRef

- .circleci/config.yml
circleci machine image `ubuntu-2004:202201-02` is being deprecated https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
Create tag following `/^v.*/` regexp, and circleci should push image to quay.io. 
I added custom (temporary) tag `v0.12.1-this-is-a-test` and [circleci job](https://app.circleci.com/pipelines/github/3scale/3scale-operator/6577/workflows/7ef6a3d1-9a1c-4591-9439-af3175200c75/jobs/46515) succeeded.
> circleci: update ubuntu base image

- pkg/3scale/amp/component/zync.go
JIRA: [THREESCALE-11256](https://issues.redhat.com/browse/THREESCALE-11256)
This PR removes unnecessary RBAC from the `zync-que-role` Role. In #1007, we added get/list permissions for ReplicaSets in the `''` APIGroup **_and_** in the `apps` APIGroup. However the operator doesn't have the RBAC to grant get/list permissions to ReplicaSets in the `''` APIGroup. 
After further investigation, it was discovered that we actually don't need to grant RBAC for the `''` APIGroup because ReplicaSets will always be in the `apps` APIGroup since they're a standard type. Therefore we can safely remove that rule from the `zync-que-role` Role.
This wasn't caught when verifying #1007 because that verification was done through a local installation where the operator technically has kubeadmin permissions. …
> THREESCALE-11256 Fixed ReplicaSets RBAC

- pkg/3scale/amp/operator/system_reconciler.go
- pkg/reconcilers/pod_monitors.go
- pkg/reconcilers/pod_monitors_test.go
[THREESCALE-11344](https://issues.redhat.com//browse/THREESCALE-11344)
create an generic pod monitor mutator to apply changes to the update
- install 2.14 
- checkout the 3scale-2.14-stable branch
- install locally 
```bash
oc new-project 3scale-test
make install
make run
###
---
kind: Secret
apiVersion: v1
metadata:
data:
type: Opaque
EOF
###
###
---
metadata:
spec: …
```
> THREESCALE-11344 create an generic pod monitor mutator to apply changes to the update

- pkg/3scale/amp/component/system.go
JIRA: [THREESCALE-11338](https://issues.redhat.com/browse/THREESCALE-11338)
This PR fixes the `system-app-pre` and `system-app-post` Jobs' volumeMounts so that the Jobs can be created when rwx storage is used.
> THREESCALE-11338 Fix system lifecycle pods with rwx storage

- apis/capabilities/v1beta1/backend_types.go
- bundle/manifests/capabilities.3scale.net_backends.yaml
- config/crd/bases/capabilities.3scale.net_backends.yaml
- doc/backend-reference.md
JIRA: [THREESCALE-11346](https://issues.redhat.com/browse/THREESCALE-11346)
This PR backports #994 to the `3scale-2.14-stable` branch for the `2.14.3` release.
This PR allows users to create a Backend CR that uses the WSS protocol for the `privateBaseURL`. This was already allowed for Backends created through the 3scale portal.
2. Run the operator locally or via OLM using prebuilt image
```bash
BUNDLE_IMG=quay.io/ckyrillo/3scale-operator-bundles:threescale-11346 make bundle-run
```
3. Create a Namespace, dummy s3 Secret, and APIManager CR:
```bash
kind: Secret
apiVersion: v1
metadata:
data:
AWS_BUCKET: …
```
> THREESCALE-11346 Backport support for Backend CRs using wss protocol

- pkg/backup/apimanager_backup_options_provider.go
JIRA: [THREESCALE-10589](https://issues.redhat.com/browse/THREESCALE-10589)
This PR fixes the env var that is checked when specifying the `oc` CLI image for the APIManagerBackup procedure. It was incorrectly set to `OSE_CLI_IMAGE` when it should be set to `RELATED_IMAGE_OC_CLI`.
Eye review and passing the PROW checks should be sufficient verification.
> THREESCALE-10589 Fix env var for APIManagerBackup OC CLI image

- apis/capabilities/v1beta1/backend_types.go
- config/crd/bases/capabilities.3scale.net_backends.yaml
JIRA: [THREESCALE-10577](https://issues.redhat.com/browse/THREESCALE-10577)
This PR makes the `SystemName` field in the Backend CR immutable. This prevents an issue where previously if a user changed the `SystemName` on an already created Backend CR, a duplicate Backend would be created in the database.
Note that in the 3scale UI, the `SystemName` field is already immutable so this PR just makes the capabilities behave the same way as the UI.
1. Checkout this branch
2. Prepare for a local install:
```bash
make install
make download
kind: Secret
apiVersion: v1
metadata:
data:
AWS_REGION: …
```
> THREESCALE-10577 Make SystemName field in Backend CR immutable

- controllers/capabilities/developeraccount_controller.go
- controllers/capabilities/developeraccount_threescale_reconciler.go
- controllers/capabilities/developeruser_controller.go
- controllers/capabilities/developeruser_threescale_reconciler.go
JIRA: [THREESCALE-10875](https://issues.redhat.com/browse/THREESCALE-10875)
This PR hardens the DeveloperAccount and DeveloperUser capabilities by implementing the following:
1. Fixes a flaky issue where the porta call to create accounts was getting a 409 response even though the account was correctly created in 3scale.
2. Adds an annotation, `accountId`, to the DeveloperAccount CR to fix broken backup and restore behavior.
3. Adds an annotation, `userId`, to the DeveloperUser CR to fix broken backup and restore behavior.
1. Checkout this branch
2. Prepare for a local install:
```bash
make install
make download
kind: Secret
apiVersion: v1
metadata:
data: …
```
> THREESCALE-10875 Fix DeveloperAccount/DeveloperUser Backup and Restore

- doc/redis-sentinel-tls.md
Jira: https://issues.redhat.com/browse/THREESCALE-11526
New document that  provides an overview of Redis Sentinel with TLS, detailing the installation and configuration process (without using a Helm Chart).
> THREESCALE-11526 - Redis Sentinel with TLS for Porta and Backend

- controllers/capabilities/backend_threescale_reconciler.go
- controllers/capabilities/developeraccount_threescale_reconciler.go
- controllers/capabilities/product.go
- controllers/capabilities/product_threescale_reconciler.go
- controllers/capabilities/tenant_threescale_reconciler.go
- go.mod
- go.sum
- pkg/controller/helper/backendapi_entity.go
- pkg/controller/helper/product_entity.go
- pkg/helper/annotations.go
https://issues.redhat.com/browse/THREESCALE-11541
Verification:
- This PR temporary has go mod updated to use porta client build from: https://github.com/3scale/3scale-porta-go-client/pull/65
Scenario 1 - 2.16 creation of capabilities
Install 3scale:
Local installation of 3scale is fine,
- Run:
```
make install
make download
kind: Secret
apiVersion: v1
metadata:
data:
type: Opaque
EOF
cat << …
```
> THREESCALE-11541 add managed-by operator flag

- controllers/capabilities/application_controller.go
- pkg/reconcilers/base_reconciler.go
Jira: https://issues.redhat.com/browse/THREESCALE-11633
Verification:
Install 3scale:
- run `make cluster/prepare/local`
- run:
```
kind: Secret
apiVersion: v1
metadata:
data:
type: Opaque
EOF
metadata:
name: 3scale
spec:
externalComponents:
backend:
redis: true
system:
database: true
redis: true
wildcardDomain: …
```
> THREESCALE-11633 fix application controller nil pointer

- Makefile
- go.mod
- go.sum
- pkg/helper/redis_database_version.go
- pkg/helper/redis_database_version_helper.go
- pkg/helper/redis_database_version_test.go
- pkg/helper/requirements_common_helper.go
- pkg/helper/requirements_common_helper_test.go
- pkg/helper/system_database_helper.go
- pkg/helper/system_database_versions.go
Fix https://issues.redhat.com/browse/THREESCALE-11209
Previously we created new pod in the same namespace as 3scale instance, but now we moved to golib and requests come from operator itself so requests to DB(s) will not be resolved. Hence, required to verify with OLM
* Checkout this branch
* Run `make cluster/prepare/local`
* Create new catalog
```
cat << EOF | oc create -f -                   
apiVersion: operators.coreos.com/v1alpha1     
kind: CatalogSource                           
metadata:                                     
name: threescale-dev                        
namespace: openshift-marketplace            
spec:                                         
sourceType: grpc                            
image: quay.io/an_tran/3scale-index:v0.14.0
EOF …
```
> THREESCALE-11209 Refactor preflight to use golib

- doc/apimanager-reference.md
- doc/operator-user-guide.md
- pkg/3scale/amp/component/backend.go
- pkg/3scale/amp/component/system.go
Fix https://issues.redhat.com/browse/THREESCALE-11021
Mostly copied from Valery's commit #1048 but removing unnecessary parts
1. Checkout this branch
2. Prepare local env
```
make cluster/prepare/local
```
3. Create apim
```
kind: Secret
apiVersion: v1
metadata:
data:
type: Opaque
EOF
metadata:
name: 3scale
spec: …
```
> THREESCALE-11021 add redis ACL credentials to system and backend

- .circleci/config.yml
- Makefile
- config/dev-databases/system-mysql/kustomization.yaml
fix `make cluster/create/system-mysql`
- run  `make cluster/create/system-mysql` against a cluster
- confirm that it completes successfully 
```bash
make cluster/create/system-mysql
make[1]: Entering directory '/home/austincunningham/repo/3scale-operator'
sed "s/\$(NAMESPACE)/3scale-test/g" ./config/dev-databases/system-mysql/secret.yaml > ./config/dev-databases/system-mysql/secret-processed.yaml
kustomize build ./config/dev-databases/system-mysql | kubectl apply -f -
secret/system-database created
service/system-mysql created
persistentvolumeclaim/system-mysql-pvc created
deployment.apps/system-mysql created
rm ./config/dev-databases/system-mysql/secret-processed.yaml
make[1]: Leaving directory '/home/3scale-operator'
```
> THREESCALE-11757 fix local dev make cluster/create/system-mysql

- pkg/3scale/amp/component/zync.go
Implements https://issues.redhat.com/browse/THREESCALE-11758
> THREESCALE-11758: Add environment variable to zync-database container to redirect all logs to stdout

- controllers/capabilities/applicationauth_controller.go
- fix typo in logging
- Fixes #1076
> Fix: #1076. Typo in logging

- pkg/helper/redis_database_version.go
- pkg/helper/redis_database_version_helper.go
- pkg/helper/redis_database_version_test.go
Fix https://issues.redhat.com/browse/THREESCALE-11850
* Checkout this branch
* Modify system-redis secret as follow
```diff
diff --git a/config/dev-databases/system-redis/secret.yaml b/config/dev-databases/system-redis/secret.yaml
index 4af6d7c4..f75260f3 100644                                                                           
--- a/config/dev-databases/system-redis/secret.yaml                                                       
+++ b/config/dev-databases/system-redis/secret.yaml                                                       
@@ -3,7 +3,7 @@ kind: Secret                                                                              
metadata:                                                                                                
name: system-redis …
```
> THREESCALE-11850  Preflight check fails on redis-sentinel

- pkg/3scale/amp/operator/backend_reconciler.go
- pkg/3scale/amp/operator/system_reconciler.go
- pkg/3scale/amp/operator/zync_reconciler.go
Backport #1103  to 2.16 branch
> Use correct volume/volumeMount mutator (2.16)

- bundle/manifests/3scale-operator.clusterserviceversion.yaml
- config/dev-databases/system-postgresql/deployment.yaml
- config/dev-databases/system-postgresql/kustomization.yaml
- config/manager/manager.yaml
- config/manifests/bases/3scale-operator.clusterserviceversion.yaml
- config/requirements/operator-requirements.yaml
- pkg/3scale/amp/component/images.go
https://issues.redhat.com/browse/THREESCALE-11897
Including:
* Bump zync-db to PostgreSQL 15
* Bump dev PostgreSQL to 15
* Change preflight requirement to PostgreSQL 15
* Checkout this PR
* Prepare local env
```
DEV_SYSTEM_DB_POSTGRES=true make cluster/prepare/local
```
* Install APIM
```
kind: Secret
apiVersion: v1
metadata:
data:
type: Opaque
EOF
apiVersion: …
```
> THREESCALE-11897 - Bump PostgreSQL to version 15

- pkg/3scale/amp/operator/system_reconciler.go
Fix https://issues.redhat.com/browse/THREESCALE-11951
* Checkout this branch
* Prepare 3scale
```bash
make cluster/prepare/local
```
* Install APIM
```bash
kind: Secret
apiVersion: v1
metadata:
data:
type: Opaque
EOF
metadata:
name: 3scale
spec:
wildcardDomain: $DOMAIN
system:
fileStorage: …
```
> Only reconcile DB's TLS volume

- pkg/3scale/amp/operator/system_reconciler.go
> THREESCALE-11951 - Only reconcile DB's TLS volume (2.16)
