.circleci/config.yml, pkg/3scale/amp/Makefile
Merges the branch into master (PR #15 was not done into master)
=> Local operator sdk command on ci

Gopkg.lock, pkg/controller/tenant/internal_reconciler.go, pkg/controller/tenant/tenant_controller.go
Tenant provider secret generated by tenant controller has two fields:
* `token` with tenant's *provider_key*
* `adminURL` with tenant's *admin domain url*
=> Tenant secret fields

test/e2e/apimanager_controller_test.go, test/e2e/full_test.go
Update E2E tests to use new APIManager fields organization
=> E2e hierarchized apimanager

pkg/controller/apimanager/apimanager_controller.go
This commit removes the printing of the full objects to avoid
log verbosity.
It also adds object namespace and name when printing the objects.
=> Improve APIManager controller logging

pkg/3scale/amp/operator/mysql.go, pkg/3scale/amp/operator/secretutils.go, pkg/controller/apimanager/apimanager_controller.go, pkg/controller/apimanager/util.go
This PR makes secrets not being updated when no differences are detected. Differences are calculated from a set of specific fields that are taken into account
=> Apimanager secret reconciliation changes

pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml, pkg/3scale/amp/component/system.go
This PR enables System's custom policy registry feature by default in rolling_updates yaml file of the 'system' ConfigMap
=> Add system policy registry setting

pkg/apis/capabilities/v1alpha1/api_types.go, pkg/apis/capabilities/v1alpha1/mappingrule_types.go, pkg/apis/capabilities/v1alpha1/metric_types.go
fixes https://github.com/3scale/3scale-operator/issues/96
=> Use FriendlyName instead of SystemName for metrics

pkg/apis/capabilities/v1alpha1/api_types.go, pkg/apis/capabilities/v1alpha1/binding_types.go, pkg/controller/binding/binding_controller.go, test/e2e/full_test.go
Fixes https://github.com/3scale/3scale-operator/issues/93
=> Use the helper function for creating a porta client

deploy/crds/capabilities_v1alpha1_plan_crd.yaml, doc/api-crd-reference.md, doc/user-guide.md, pkg/apis/capabilities/v1alpha1/plan_types.go, test/e2e/full_test.go, test/e2e/manifests/plans.yml
fixes https://github.com/3scale/3scale-operator/issues/102
=> Corrected typo aprovalRequired -> approvalRequired

.circleci/config.yml, Makefile
On master branch, tag operator images (after tests successfully pass) as `master` and `latest`
=> tag master and latest operator images

pkg/apis/capabilities/v1alpha1/api_types.go, pkg/helper/helper.go
fixes https://github.com/3scale/3scale-operator/issues/105
=> Adds default port number to the staging/production urls when using apicastOnPrem integration method

.circleci/config.yml
=> Test circleci docker layer caching

pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml, pkg/3scale/amp/component/system.go
=> [rolling_updates] Add service_mesh_integration: true

pkg/controller/apimanager/apimanager_controller.go
We create a Client Reader that directly queries the API server
without going to the Cache provided by the Manager's split client because
there are some resources that do not implement Watch (like ImageStreamTag)
and the Manager's Client always tries to use the Cache when reading.
This is needed at least to manage ImageStreamTag modifications during
upgrades that we will need to perform.
=> Add direct client reader to Kubernetes API in apimanager reconciler

.gitignore, deploy/olm-catalog/3scale-operator/3scale-operator.v0.3.0.clusterserviceversion.yaml
OLM requires description and displayName fields to be present
Signed-off-by: Babak Mozaffari <bmozaffa@redhat.com>
=> OLM requires description and displayName fields to be present

pkg/3scale/amp/component/ampimages.go, pkg/3scale/amp/component/apicast.go, pkg/3scale/amp/component/backend.go, pkg/3scale/amp/component/buildconfigs.go, pkg/3scale/amp/component/evaluation.go, pkg/3scale/amp/component/highavailability.go, pkg/3scale/amp/component/memcached.go, pkg/3scale/amp/component/mysql.go, pkg/3scale/amp/component/redis.go, pkg/3scale/amp/component/s3.go, pkg/3scale/amp/component/system.go, pkg/3scale/amp/component/system_mysql_image.go, pkg/3scale/amp/component/system_postgresql.go, pkg/3scale/amp/component/system_postgresql_image.go, pkg/3scale/amp/component/zync.go, pkg/apis/common/kubernetes_types.go, pkg/controller/apimanager/apimanager_controller.go, pkg/helper/helper.go
Avoid the use of RawExtension and unnecessary conversions of objects, other than for templates
Original PR https://github.com/3scale/3scale-operator/pull/138
=> Kubernetes objects

deploy/olm-catalog/3scale-operator/3scale-operator.v0.3.0.clusterserviceversion.yaml, go.mod, go.sum, pkg/apis/apps/v1alpha1/apimanager_types.go, pkg/controller/apimanager/apimanager_controller.go
Use of pie chart to show deployment progress
Add wildcard domain value to OLM page
Signed-off-by: Babak Mozaffari <bmozaffa@redhat.com>
=> Further enhancements to the OLM integration

pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-postgresql.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml, pkg/3scale/amp/component/zync.go
=> Add patch route verb for zync

pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-postgresql.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/productized_templates/amp/amp.yml, pkg/3scale/amp/component/zync.go
cherry-picked same contents than PR #166
=> Update zync route permissions

pkg/3scale/amp/template/adapters/images.go, pkg/3scale/amp/template/adapters/redis.go, pkg/3scale/amp/template/adapters/system-mysql-image.go, pkg/3scale/amp/template/adapters/system-postgresql-image.go
Refactor to unify the source of the image URLs on both templates and operator
=> Unify image URLs source between templates and operator

pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp.yml, pkg/3scale/amp/operator/ampimages.go, pkg/3scale/amp/operator/system.go, pkg/3scale/amp/operator/system_mysql_image.go, pkg/3scale/amp/operator/system_postgresql_image.go, pkg/3scale/amp/product/images.go, pkg/3scale/amp/template/adapters/images.go, pkg/3scale/amp/template/adapters/redis.go, pkg/3scale/amp/template/adapters/system-mysql-image.go, pkg/3scale/amp/template/adapters/system-postgresql-image.go, pkg/3scale/amp/template/basic_template.go
* Updated 3scale release version from 2.6.0 to 2.6
* Product 3scale release version in a single place
=> Updated 3scale release version from 2.6.0 to 2.6 

pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp.yml, pkg/3scale/amp/product/images.go, pkg/3scale/amp/product/upstream.go
Master branch  should use nightly images
=> master uses upstream nightly images

pkg/3scale/amp/cmd/template.go, pkg/3scale/amp/template/adapters/apicast.go, pkg/3scale/amp/template/adapters/backend.go, pkg/3scale/amp/template/adapters/eval.go, pkg/3scale/amp/template/adapters/ha.go, pkg/3scale/amp/template/adapters/images.go, pkg/3scale/amp/template/adapters/memcached.go, pkg/3scale/amp/template/adapters/redis.go, pkg/3scale/amp/template/adapters/s3.go, pkg/3scale/amp/template/adapters/system-mysql-image.go, pkg/3scale/amp/template/adapters/system-mysql.go, pkg/3scale/amp/template/adapters/system-postgresql-image.go, pkg/3scale/amp/template/adapters/system-postgresql.go, pkg/3scale/amp/template/adapters/system.go, pkg/3scale/amp/template/adapters/zync.go, pkg/3scale/amp/template/amp.go, pkg/3scale/amp/template/ampeval.go, pkg/3scale/amp/template/ampevals3.go, pkg/3scale/amp/template/ampha.go, pkg/3scale/amp/template/amppostgresql.go, pkg/3scale/amp/template/amps3.go, pkg/3scale/amp/template/factory.go
Remove list of templates from factory. Each template factory register itself to be available to the CLI.
=> refactor template factories

pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp.yml, pkg/3scale/amp/operator/ampimages.go, pkg/3scale/amp/operator/system.go, pkg/3scale/amp/operator/system_mysql_image.go, pkg/3scale/amp/operator/system_postgresql_image.go, pkg/3scale/amp/product/images.go, pkg/3scale/amp/template/adapters/images.go, pkg/3scale/amp/template/adapters/redis.go, pkg/3scale/amp/template/adapters/system-mysql-image.go, pkg/3scale/amp/template/adapters/system-postgresql-image.go, pkg/3scale/amp/template/basic_template.go
This PR backports the https://github.com/3scale/3scale-operator/pull/175 PR from master that we need in CR1
=> [2] 2.6 stable backport amprelease simplification

pkg/3scale/amp/manual-templates/amp/apicast.yml
Use registry.redhat.io image for apicast template in 2.6-stable-prod branch
=> 2.6 stable prod updateapicast

pkg/3scale/amp/component/ampimages.go, pkg/3scale/amp/component/system_mysql_image.go
Backports PRs #198 and #199 fixes related to ImageStreams configuration
=> 2.6-stable backport ImageStream fixes

pkg/3scale/amp/component/ampimages.go, pkg/3scale/amp/component/system_mysql_image.go
Backports PRs #198 and #199 fixes related to ImageStreams configuration
=> 2.6 stable prod backport ImageStream fixes

pkg/3scale/amp/operator/backend.go
=> [FIX] backend redis secret read - backport to 2.6-stable

pkg/3scale/amp/operator/backend.go
=> [FIX] backend redis secret read- backport to 2.6-stable-prod

pkg/apis/apps/v1alpha1/apimanager_types.go
This PR fixes change detection being lost in some cases when setting System defaults
=> Fix setSystemSpecDefaults change detection

pkg/apis/apps/v1alpha1/apimanager_types.go
Simplify defaults initialization methods
=> Refactor APIManager defaults initialization methods

doc/dependency_decisions.yml, licenses.xml
Added:
github.com/onsi/ginkgo
github.com/onsi/gomega
into dependency_decisions.yml file.
licenses.xml also updated
=> Update licenses.xml and dependency_decisions

.circleci/config.yml, Makefile
Add `oc observe pods` to e2e tests.
=> Fix test observability

.circleci/config.yml
Apply some changes in CircleCI config to be compliant with current CircleCI configuration version
=> Update CircleCI configuration elements to expected configuration values

pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp.yml, pkg/3scale/amp/component/system.go, pkg/3scale/amp/operator/system.go, pkg/3scale/amp/operator/system_reconciler.go, pkg/controller/apimanager/upgrade_26_to_27.go
Backport PR #250 to 2.7-stable-prod branch
=> 2.7 stable prod backport system's migrations upgrade fix

pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp.yml, pkg/3scale/amp/component/system.go, pkg/3scale/amp/operator/system.go, pkg/3scale/amp/operator/system_reconciler.go, pkg/controller/apimanager/upgrade_26_to_27.go
Backport PR #250 to 2.7-stable branch
=> 2.7 stable backport system's migrations upgrade fix

pkg/controller/apimanager/upgrade_26_to_27.go
Until now, for every release AMP_RELEASE environment variable was updated to the new 3scale version as this variable was used to display the version in system's UI.
We lacked this part on the operator's upgrade mechanism. In templates it's already documented on the upgrade documentation.
System team is working on changing the behaviour on how the version is displayed and in fact currently they are not really relying on this value and might not be needed but the new mechanism seems it not being applied either at this moment, and they might not change it/fix it for this release so we are adding this change so they can resort to this in case they need to revert back to the old behavior.
=> Upgrade System's AMP_RELEASE on operator upgrade

pkg/controller/apimanager/upgrade_26_to_27.go
=> [2.7-stable-prod] Upgrade System's AMP_RELEASE on operator upgrade

pkg/controller/apimanager/upgrade_26_to_27.go
=> [2.7-stable] Upgrade System's AMP_RELEASE on operator upgrade

pkg/3scale/amp/operator/redis_reconciler.go, pkg/3scale/amp/operator/system_mysql_image_reconciler.go, pkg/3scale/amp/operator/system_mysql_reconciler.go, pkg/3scale/amp/operator/system_postgresql_image_reconciler.go, pkg/controller/apimanager/apimanager_controller.go
Fix system database postgresql DC being created when `spec.highAvailability.enabled`
=> fix databaseless reconciliation

pkg/3scale/amp/operator/redis_reconciler.go, pkg/3scale/amp/operator/system_mysql_image_reconciler.go, pkg/3scale/amp/operator/system_mysql_reconciler.go, pkg/3scale/amp/operator/system_postgresql_image_reconciler.go, pkg/controller/apimanager/apimanager_controller.go
Fix system database postgresql DC being created when `spec.highAvailability.enabled`
=> 2.7 stable backport fix databaseless reconciliation

pkg/3scale/amp/operator/redis_reconciler.go, pkg/3scale/amp/operator/system_mysql_image_reconciler.go, pkg/3scale/amp/operator/system_mysql_reconciler.go, pkg/3scale/amp/operator/system_postgresql_image_reconciler.go, pkg/controller/apimanager/apimanager_controller.go
Fix system database postgresql DC being created when `spec.highAvailability.enabled`
=> 2.7 stable prod backport fix databaseless reconciliation

pkg/3scale/amp/component/highavailability.go, pkg/controller/apimanager/apimanager_controller.go
Fix system database postgresql DC being created when spec.highAvailability.enabled
=> 2.6 stable prod backport fix databaseless postgresql deployment

pkg/3scale/amp/component/highavailability.go, pkg/controller/apimanager/apimanager_controller.go
Fix system database postgresql DC being created when `spec.highAvailability.enabled`
=> 2.6 stable backport fix databaseless postgresql deployment

.circleci/config.yml
Early detection when nightly images break 3scale deployment
=> ci nightly: run template and operator e2e tests

pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/component/highavailability.go, pkg/3scale/amp/component/highavailability_options_builder.go, pkg/3scale/amp/template/adapters/ha.go
Template to deploy 3scale with external databases missed sentinels template parameters
=> Include sentinels in external database templates

deploy/olm-catalog/3scale-operator-master/3scale-operator-master.v0.0.0.clusterserviceversion.yaml, deploy/operator.yaml
* Remove ImagePullPolicy: Always due to fixed tags used for operator now
* Change maturity from alpha to stable in operator's CSV
=> Update deployment csv

go.mod
Commit changes that are produced when reexecuting the vendoring of dependencies with the current code contents to reflect and up to date status
The executed commands have been:
```
rm -rf vendor
rm go.sum
go clean -modcache
GO111MODULE=on go mod vendor
GO111MODULE=on go mod tidy
```
=> Update dependencies with to match current state of the code

Makefile
Makes it convenient to change the value of them in one place.
Useful when you need to change them or temporarily change them
for some test.
=> Makefile: move binary names into variables

.circleci/config.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp.yml, pkg/3scale/amp/product/3scale_release.go, test/e2e/apimanager_controller_test.go
Template and operator test default images instead of enforcing nightly images. 
Stable branch tests were testing nightly images
=> template and operator test default images

deploy/crds/apps.3scale.net_v1alpha1_apimanager_cr_s3.yaml
Use new field names instead of the deprecated ones
=> Update APIManager S3 CR example fields for S3 configuration

deploy/crds/apps_v1alpha1_apimanager_cr_s3.yaml
=> 3scale28stable backport PR #345

deploy/crds/apps_v1alpha1_apimanager_cr_s3.yaml
=> 3scale28stableprod backport PR #345

pkg/3scale/amp/component/ampimages.go, pkg/3scale/amp/component/apicast.go, pkg/3scale/amp/component/backend.go, pkg/3scale/amp/component/highavailability.go, pkg/3scale/amp/component/memcached.go, pkg/3scale/amp/component/redis.go, pkg/3scale/amp/component/s3.go, pkg/3scale/amp/component/system.go, pkg/3scale/amp/component/system_mysql.go, pkg/3scale/amp/component/system_mysql_image.go, pkg/3scale/amp/component/system_postgresql.go, pkg/3scale/amp/component/system_postgresql_image.go, pkg/3scale/amp/component/zync.go, pkg/3scale/amp/template/adapters/apicast.go, pkg/3scale/amp/template/adapters/backend.go, pkg/3scale/amp/template/adapters/ha.go, pkg/3scale/amp/template/adapters/images.go, pkg/3scale/amp/template/adapters/memcached.go, pkg/3scale/amp/template/adapters/redis.go, pkg/3scale/amp/template/adapters/s3.go, pkg/3scale/amp/template/adapters/system-mysql-image.go, pkg/3scale/amp/template/adapters/system-mysql.go, pkg/3scale/amp/template/adapters/system-postgresql-image.go, pkg/3scale/amp/template/adapters/system-postgresql.go, pkg/3scale/amp/template/adapters/system.go, pkg/3scale/amp/template/adapters/zync.go, pkg/helper/envvarutils.go
This PR refactors the following templates-related code into the templates package:
* Objects list created by each component in the templates
* Post-Processing methods (which only apply to templates)
=> Refactor templates-related code into templates package

doc/operator-user-guide.md
=> Backport PR #353 to 3scale-2.8-stable-prod

doc/operator-user-guide.md
=> Backport PR #353 to 3scale-2.8-stable branch

deploy/crds/apps.3scale.net_v1alpha1_apimanagerbackup_cr.yaml, deploy/crds/apps.3scale.net_v1alpha1_apimanagerrestore_cr.yaml, test/crds/crd_validation_test.go
Add APIManagerBackup and APIManagerRestore to the CRD tests
=> Add backup restore crd tests

Makefile, doc/dependency_decisions.yml, licenses.xml
=> monitoring: add new licenses

doc/operator-user-guide.md
Update operator user guide to explain how to set a custom storage class when deploying
System using PVC for its FileStorage
=> Add documentation on how to deploy custom storage class for System's FileStorage

doc/apimanager-reference.md, doc/apimanagerbackup-reference.md, doc/apimanagerrestore-reference.md
Update obsolete/broken links to K8s API reference documentation
=> Update obsolete K8s API reference doc links

pkg/3scale/amp/component/backend.go, pkg/assets/assets.go
=> Fix monitoring tools

pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp.yml, pkg/3scale/amp/component/apicast.go, pkg/3scale/amp/component/apicast_options.go, pkg/3scale/amp/component/backend.go, pkg/3scale/amp/component/backend_options.go, pkg/3scale/amp/operator/apicast_options_provider.go, pkg/3scale/amp/operator/apicast_options_provider_test.go, pkg/3scale/amp/operator/backend_options_provider.go, pkg/3scale/amp/operator/backend_options_provider_test.go, pkg/3scale/amp/operator/upgrade.go, pkg/helper/envvarutils.go
Upgrade path for monitoring resources.
Added required changes to support monitoring only with operator.
=> Monitoring upgrade

pkg/3scale/amp/component/apicast_monitoring.go, pkg/3scale/amp/component/backend_monitoring.go, pkg/3scale/amp/component/zync_monitoring.go, pkg/3scale/amp/operator/backend_reconciler.go
* Add new rules for backend worker, backend listener, zync
* Fix backend worker rules
* Add new rules for zync and zync-que
* Add new rules for apicast
=> Improve 3scale monitoring rules

deploy/olm-catalog/3scale-operator-master/0.0.0/3scale-operator-master.v0.0.0.clusterserviceversion.yaml, deploy/role.yaml
Allow delete of monitoring resources
=> Fix monitoring permissions

pkg/controller/backend/status_reconciler.go
Fix https://issues.redhat.com/browse/THREESCALE-5644
=> [backport-438] Fix backend status sync condition

doc/apimanagerbackup-reference.md, doc/operator-backup-and-restore.md, doc/operator-user-guide.md
Backports PR #437 to 3scale-2.9-stable-prod branch
=> [backport-437] Update APIManagerBackup PVC requirements documentation

deploy/olm-catalog/3scale-operator-master/0.0.0/3scale-operator-master.v0.0.0.clusterserviceversion.yaml, deploy/role.yaml
Additional role permissions needed for APIManagerBackup/APIManagerRestore
=> Add K8s jobs role permissions

doc/development.md, doc/operator-backup-and-restore.md, doc/operator-capabilities.md
Observed a few grammatical changes. Suggesting the same.
=> Document update

pkg/controller/backend/backend_controller.go, pkg/controller/product/product_controller.go
https://issues.redhat.com/browse/THREESCALE-5878
=> product and backend CRD: fix status update on validation errors

pkg/controller/helper/backendapi_remote_index.go
=> product controller: fix backend index build

doc/apimanager-reference.md, doc/apimanagerbackup-reference.md, doc/apimanagerrestore-reference.md, doc/backend-reference.md, doc/product-reference.md, doc/tenant-reference.md
Add table of contents index to all API references.
=> 3scale CRD reference TOC

doc/development.md
=> Update development documentation to include clusterrole creation/cleanup

pkg/3scale/amp/component/apicast_monitoring.go
As requested in https://github.com/3scale/3scale-operator/pull/484
=> Change ThreescaleApicastWorkerRestart monitoring alert to warning

deploy/olm-catalog/3scale-operator-master/0.0.0/3scale-operator-master.v0.0.0.clusterserviceversion.yaml
To comply with what some of our operators pipelines check
=> Update CSV support value

pkg/3scale/amp/operator/upgrade.go
I have compared monitoring resources differences between 2.9 and 2.10 that require upgrading procedure not implemented currently. I found:
=> upgrade apicast and system sidekiq prometheus rules

pkg/3scale/amp/operator/base_apimanager_logic_reconciler.go
Backport conditional monitoring logging based on kinds existence for `has*Resource` types in base APIManager logic reconciler
=> [backport 509,510] conditional monitoring resource check logging

Makefile, bundle/manifests/3scale-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/3scale-operator.clusterserviceversion.yaml
'nightly' tag does not exist in the case of 3scale-operator
=> Use quay.io/3scale/3scale-operator:master image

.circleci/config.yml, Makefile, doc/development.md
* add ci task to check bundle generation is not updated
* development task to deploy custom bundle in OLM
=> Enchance development tasks

pkg/3scale/amp/operator/base_apimanager_logic_reconciler.go, pkg/3scale/amp/operator/base_apimanager_logic_reconciler_test.go, pkg/controller/apimanager/apimanager_controller.go, pkg/reconcilers/base_reconciler.go, pkg/reconcilers/base_reconciler_test.go
Backport PR #527 Improve APIManager reconcile times
=> [scale-2.10-stable-prod] Backport PR #527 

bundle/manifests/3scale-operator.clusterserviceversion.yaml, config/manager/manager.yaml, pkg/3scale/amp/operator/upgrade.go, version/version.go
* operator version bump: 0.8.0
* upgrade procedure reset
=> Bump release 2.11

.circleci/config.yml, test/e2e/apimanager_controller_test.go
* e2e test from tag name
* fix circleci job to build images from any tag
=> E2e test from CR1 tag

deploy/crds/apps.3scale.net_apimanagers_crd.yaml, doc/apimanager-reference.md, pkg/3scale/amp/component/apicast.go, pkg/3scale/amp/component/apicast_options.go, pkg/3scale/amp/operator/apicast_options_provider.go, pkg/3scale/amp/operator/apicast_reconciler.go, pkg/3scale/amp/operator/backend_reconciler.go, pkg/3scale/amp/operator/memcached_reconciler.go, pkg/3scale/amp/operator/redis_reconciler.go, pkg/3scale/amp/operator/system_mysql_reconciler.go, pkg/3scale/amp/operator/system_postgresql_reconciler.go, pkg/3scale/amp/operator/system_reconciler.go, pkg/3scale/amp/operator/upgrade.go, pkg/3scale/amp/operator/zync_reconciler.go, pkg/apis/apps/v1alpha1/apimanager_types.go, pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go, pkg/helper/envvarutils.go, pkg/reconcilers/deploymentconfig.go, pkg/reconcilers/deploymentconfig_test.go
Backport #548 
Adds APIManager CRD change, hence, requires metadata update in productized bundle.
=> Backport 548 apicast workers

pkg/3scale/amp/component/apicast_monitoring.go, pkg/3scale/amp/component/apicast_options.go, pkg/3scale/amp/component/backend_monitoring.go, pkg/3scale/amp/component/backend_options.go, pkg/3scale/amp/component/generic_monitoring.go, pkg/3scale/amp/component/system_monitoring.go, pkg/3scale/amp/component/system_options.go, pkg/3scale/amp/component/zync_monitoring.go, pkg/3scale/amp/component/zync_options.go, pkg/3scale/amp/operator/apicast_options_provider.go, pkg/3scale/amp/operator/apicast_options_provider_test.go, pkg/3scale/amp/operator/apicast_reconciler.go, pkg/3scale/amp/operator/backend_options_provider.go, pkg/3scale/amp/operator/backend_options_provider_test.go, pkg/3scale/amp/operator/backend_reconciler.go, pkg/3scale/amp/operator/generic_monitoring_reconciler.go, pkg/3scale/amp/operator/system_options_provider.go, pkg/3scale/amp/operator/system_options_provider_test.go, pkg/3scale/amp/operator/system_reconciler.go, pkg/3scale/amp/operator/upgrade.go, pkg/3scale/amp/operator/zync_options_provider.go, pkg/3scale/amp/operator/zync_options_provider_test.go, pkg/3scale/amp/operator/zync_reconciler.go, pkg/3scale/amp/template/adapters/apicast.go, pkg/3scale/amp/template/adapters/backend.go, pkg/3scale/amp/template/adapters/system.go, pkg/3scale/amp/template/adapters/zync.go
=> Backport 556 labels monitoring

.circleci/config.yml
Reverts 3scale/3scale-operator#572
=> Revert "Custom build"

go.mod, go.sum
=> Backport fix CVE-2020-14040

doc/operator-user-guide.md
I'm not sure how to clearly express the requirement for the wildcard domain. You can see my attempt here. I will welcome any other suggestions though.
=> clarify wildcard domain

.circleci/config.yml, deploy/operator.yaml, doc/template-user-guide.md, pkg/3scale/amp/auto-generated-templates/amp/amp-eval-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-eval.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-ha.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-postgresql.yml, pkg/3scale/amp/auto-generated-templates/amp/amp-s3.yml, pkg/3scale/amp/auto-generated-templates/amp/amp.yml, pkg/3scale/amp/component/images.go, test/e2e/apimanager_controller_test.go
Update images used in CI to 3scale-2.10.0-GA
=> Update 3scale-2.10-stable CI images config

bundle/manifests/3scale-operator.clusterserviceversion.yaml, config/manifests/bases/3scale-operator.clusterserviceversion.yaml
=> [backport-606] fix csv maintainer email

doc/development.md
This PR streamlines overall developer experience
by simplifying the documentation
Signed-off-by: Krishna Harsha Voora <krishvoor@in.ibm.com>
=> Updates Documentation

Makefile
Fix YQ version from the makefile targets. Avoid issues if installed `yq` version is higher than `v3.x`
=> Fix makefile yq version

controllers/apps/apimanager_controller.go
Status was not updated when spec reconciliation returned error. The only way to debug errors was looking at the logs of the operator. 
With this change, on spec reconciliation error, the status is being updated with `Available` condition set to `false`. 
This reminds me that we still have a TODO which is try to set the error root cause in the status section
=> apimanager: update status regardless spec error

Dockerfile, Makefile
=> [Backport 613] Enable ppc

pkg/controller/helper/application_plan_entity_test.go, pkg/controller/helper/backend_list_test.go, pkg/controller/helper/backendapi_entity_test.go, pkg/controller/helper/backendapi_remote_index_test.go, pkg/controller/helper/developeruser_test.go, pkg/controller/helper/helper_test.go, pkg/controller/helper/lookup_provider_account_test.go, pkg/controller/helper/product_entity.go, pkg/controller/helper/product_entity_test.go, pkg/controller/helper/product_list_test.go, pkg/controller/helper/threescale_api_test.go, pkg/controller/helper/url_test.go
Backport #589 
Required to backport #643
=> [Backport 589] unittests

.circleci/config.yml
=> [Backport 649] fix circleci update failure

pkg/helper/labels.go, pkg/helper/version_parser.go, pkg/helper/version_parser_test.go
=> [Backport 660] fix version parser

pkg/controller/helper/threescale_api.go
=> [backport 681] http client respects http prxy env vars

bundle/manifests/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, config/prometheus/monitor.yaml
Add missing label to servicemonitor to monitor operator metrics
=> fix servicemonitor selector

bundle/manifests/threescale-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml, config/prometheus/monitor.yaml
=> [Backport 696] fix servicemonitor selector

bundle/manifests/3scale-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/default/manager_metrics_patch.yaml, config/default/manager_webhook_patch.yaml, config/manager/manager.yaml
=> [Backport 699] change operator deployment name

controllers/capabilities/backend_controller.go, controllers/capabilities/product_controller.go
https://issues.redhat.com/browse/THREESCALE-7900
=> backend, product controllers: fix reconciliation on error

apis/capabilities/v1beta1/product_types.go, controllers/capabilities/backend_controller.go, controllers/capabilities/product_controller.go
Fixed some lint warnings showed up in my IDE
=> fix lint issues

doc/prometheusrules/apicast.yaml, doc/prometheusrules/backend-listener.yaml, doc/prometheusrules/backend-worker.yaml, doc/prometheusrules/system-app.yaml, doc/prometheusrules/system-sidekiq.yaml, doc/prometheusrules/threescale-kube-state-metrics.yaml, doc/prometheusrules/zync-que.yaml, doc/prometheusrules/zync.yaml, pkg/3scale/amp/component/apicast_monitoring.go, pkg/3scale/amp/component/backend_monitoring.go, pkg/3scale/amp/component/generic_monitoring.go, pkg/3scale/amp/component/system_monitoring.go, pkg/3scale/amp/component/zync_monitoring.go
=> Sop annotations in alerts

CHANGELOG.md, pkg/3scale/amp/operator/upgrade.go, version/version.go
* bump operator version to 0.10.0
* Add CHANGELOG for 0.8.0 and 0.9.0
* reset upgrade procedure
=> Bump release 2.13

controllers/apps/apimanagerrestore_logic_reconciler.go
The APIManagerRestore controller, creates a job to resync zync domains. That job needs `system-sidekiq` pod up&running. The controller  creates the mentioned job with default [Pod backoff failure policy](https://issues.redhat.com/browse/THREESCALE-8476#pod-backoff-failure-policy].)
That means that the job will try 6 times before giving up. That last try happens 6 minutes after the job was created. If the system-sidekiq is not up&running in 6 minutes, the restore process would fail, as [Marian Ganisin](https://issues.redhat.com/secure/ViewProfile.jspa?name=mganisin%40redhat.com) found.
This PR implements a waiting step for the `system-sidekiq` deployment before running the job for resyncing zync domains.
Fixes https://issues.redhat.com/browse/THREESCALE-8476
Those defined in …
=> fix restore resync job

controllers/apps/apimanagerrestore_logic_reconciler.go
=> [backport 766] fix restore resync job

bundle/manifests/3scale-operator.clusterserviceversion.yaml, config/manager/manager.yaml, pkg/3scale/amp/component/images.go, pkg/restore/apimanager_restore.go
Backport #768 
Jira: https://issues.redhat.com/browse/THREESCALE-8476
=> [Backport 768] THREESCALE-8476 fix domain resync command line

pkg/3scale/amp/component/apicast.go
https://issues.redhat.com/browse/MGDAPI-4815 - Investigate adding APICast metrics to RHOAM prometheus
Use together with RHOAM PR https://github.com/integr8ly/integreatly-operator/pull/2981
=> MGDAPI-4815 - Investigate adding APICast metrics to RHOAM prometheus

apis/apps/v1alpha1/apimanager_types.go, doc/apimanager-reference.md
Include new ServiceCacheSize fields in documentation
=> THREESCALE-8749 (docs): ServiceCacheSize

CHANGELOG.md, bundle/manifests/3scale-operator.clusterserviceversion.yaml, config/manager/manager.yaml, pkg/3scale/amp/product/3scale_release.go, version/version.go
* bump operator version to 0.11.0
* Add CHANGELOG for 0.10.0
* ~reset upgrade procedure~ (not needed) :dancers:
=> bump to 3scale 2.14 and version 0.11.0

pkg/3scale/amp/component/backend.go, pkg/reconcilers/deploymentconfig.go
Reverts 3scale/3scale-operator#860
=> Revert "THREESCALE-7864 set async by default on backend work"

.circleci/config.yml, Dockerfile, Makefile, doc/development.md, go.mod, go.sum, pkg/3scale/amp/operator/base_apimanager_logic_reconciler.go, pkg/assets/bindata.go, pkg/controller/helper/helper_test.go, pkg/helper/webconsole.go, pkg/reconcilers/base_reconciler.go
To verify:
- prow checks/circle CI checks should be efficient
- alternatively provision 4.11 OCP/OSD and install the operator following dev guide
=> THREESCALE-10229 bump 2.12 go version

doc/operator-application-capabilities.md
Created Jira issues for that
* Dev portal SSO integration: https://issues.redhat.com/browse/THREESCALE-10369
* Admin portal SSO integration: https://issues.redhat.com/browse/THREESCALE-10368
> Application capabilities epic: https://issues.redhat.com/browse/THREESCALE-3486
=> doc: missing sso integration in admin and developer portal

pkg/3scale/amp/component/zync.go, pkg/3scale/amp/operator/backend_reconciler_test.go, pkg/3scale/amp/operator/memcached_reconciler_test.go, pkg/3scale/amp/operator/zync_options_provider.go, pkg/3scale/amp/operator/zync_options_provider_test.go, pkg/3scale/amp/operator/zync_reconciler.go, pkg/3scale/amp/operator/zync_reconciler_test.go, pkg/reconcilers/role.go, pkg/reconcilers/role_test.go
JIRA: [THREESCALE-10392](https://issues.redhat.com/browse/THREESCALE-10392)
This PR replaces the `zync`, `zync-que`, and `zync-database` DeploymentConfigs with Deployments.
1. Provision a cluster
2. Install 3scale locally using master
3. Checkout this PR
4. Re-run 3scale locally
5. Verify that the new `zync`, `zync-que`, and `zync-database` Deployments are created
6. Verify that the `zync`, `zync-que`, and `zync-database` DeploymentConfigs are deleted once the Deployments report healthy
=> THREESCALE-10392 Migrate zync DeploymentConfigs to Deployments

controllers/capabilities/proxyconfigpromote_controller.go, controllers/capabilities/proxyconfigpromote_controller_test.go
Jira: https://issues.redhat.com/browse/THREESCALE-10381
Additional checks are required when bumping from Config environment to Staging environment via ProxyConfigPromote CR. These checks will prevent bumping if no Product changes are detected. The PCP CR will also reflect this action.
- Provision a cluster
- Once ready, log in to your cluster via CLI.
- checkout this branch
- Install CRDs:
```
make install
```
- Create a new project:
```
```
- Create a new secret:
```
kind: Secret
apiVersion: v1
metadata:
namespace: threescale
data:
type: Opaque
EOF
```
- Create a new API Manager CR using …
=> THREESCALE-10381 ProxyConfigPromote CR - improve config to stage promotion

Makefile, bundle/manifests/3scale-operator.clusterserviceversion.yaml, config/manifests/bases/3scale-operator.clusterserviceversion.yaml
https://issues.redhat.com/browse/THREESCALE-10693
set maxOpenShiftVersion to 4.15
=> THREESCALE-10693 set maxOpenShiftVersion to 4.15

pkg/helper/system_database_versions.go
Jira: https://issues.redhat.com/browse/THREESCALE-10940
Verification:
Create APIM with external system database
Create Postgres db (from preflight verification doc) and secret
Edit the service of postgres to 5444 -> 5432 and edit the secret to point to port 5444.
Run, postgres should be successfully verified.
=> THREESCALE-10940 support custom postgres port number

controllers/subscription/subscription_controller.go
https://issues.redhat.com/browse/THREESCALE-10946
Verification:
- Prep catalog source pointing to this index image: quay.io/mstoklus/3scale-index:v0.0.2 (name of catalog CR "threescale")
- Install the operator by manually creating subscription CR (operator namespace is threescale):
```
cat << EOF | oc create -f - -n threescale                      
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
name: threescale-operator
spec:
channel: alpha
installPlanApproval: Automatic
name: 3scale-operator
source: threescale
sourceNamespace: openshift-marketplace
startingCSV: 3scale-operator.v0.0.2
EOF
```
- Double-check that the requirements config map is created
- No need to create APIM etc.
=> THREESCALE-10946 subscription fetch improvement

doc/operator-application-capabilities.md, doc/proxyConfigPromote-reference.md
Add status messages to proxyConfigPromote docs
=> THREESCALE-10950 add the status messages to the proxyConfigPromote docs

controllers/apps/apimanager_controller.go
https://issues.redhat.com/browse/THREESCALE-10955
Verification steps:
code review and passing e2e is fine to confirm
upgrade will be demonstrated on a separate meeting
=> THREESCALE-10955 add 2.14 to 2.15 condition

bundle/manifests/3scale-operator.clusterserviceversion.yaml, config/manager/manager.yaml, pkg/3scale/amp/component/images.go
Jira: https://issues.redhat.com/browse/THREESCALE-10956
=> THREESCALE-10956 Update CSV internal dbs for upstream

controllers/apps/apimanager_controller.go, controllers/apps/apimanager_status_reconciler.go
https://issues.redhat.com/browse/THREESCALE-10957
Verification:
=> THREESCALE-10957 improve multi minor hop message

pkg/3scale/amp/product/3scale_release.go
[THREESCALE-10882](https://issues.redhat.com//browse/THREESCALE-10882)
remove 3scale_release.go from mas branch
=> THREESCALE-10882 remove 3scale_release.go

controllers/capabilities/applicationauth_controller.go
[THREESCALE-10964](https://issues.redhat.com//browse/THREESCALE-10964)
improve the secret check on ApplicaitonAuth
- Install this branch to the 3scale-test ns
- Install a product and application via cr you can use [./setup_product](https://github.com/3scale-labs/3scale-perf-setup/blob/main/setup_product.sh)
- Create an secret called auth-secret
```bash
oc create secret generic auth-secret \
--from-literal=UserKey=""\
--from-literal=ApplicationKey=""\
--namespace=3scale-test
```
- create a applicationAuth CR
```bash
oc apply -f - <<EOF
---
apiVersion: capabilities.3scale.net/v1beta1
kind: ApplicationAuth
metadata:
name: applicationAuth-cr1
spec:
applicationCRName: application-cr 
generateSecret: true
authSecretRef: 
name: invalid-secret-name
EOF
```
- confirm that no …
=> THREESCALE-10964 improve the auth secret check

controllers/apps/apimanager_status_reconciler.go, doc/operator-user-guide.md, pkg/3scale/amp/operator/apicast_options_provider.go, pkg/3scale/amp/operator/backend_options_provider.go
Allow setting resource requirements when hpa is enabled
TBD
=> THREESCALE-1108 remove hpa override of request and limits set in apimanager CR

PROJECT, apis/apps/v1alpha1/apimanager_types.go, apis/capabilities/v1beta1/proxyconfigpromote_types.go, bundle/manifests/3scale-operator.clusterserviceversion.yaml, bundle/manifests/capabilities.3scale.net_proxyconfigpromotes.yaml, bundle/tests/scorecard/config.yaml, config/crd/bases/capabilities.3scale.net_proxyconfigpromotes.yaml, config/manifests/bases/3scale-operator.clusterserviceversion.yaml, config/samples/apps_v1alpha1_apimanager_simple.yaml, config/samples/apps_v1alpha1_apimanagerbackup.yaml, config/samples/apps_v1alpha1_apimanagerrestore.yaml, config/samples/capabilities_v1alpha1_tenant.yaml, config/samples/capabilities_v1beta1_activedoc_url.yaml, config/samples/capabilities_v1beta1_application.yaml, config/samples/capabilities_v1beta1_applicationauth.yaml, config/samples/capabilities_v1beta1_backend.yaml, config/samples/capabilities_v1beta1_custompolicydefinition.yaml, config/samples/capabilities_v1beta1_developeraccount.yaml, config/samples/capabilities_v1beta1_developeruser_admin.yaml, config/samples/capabilities_v1beta1_openapi_url.yaml, config/samples/capabilities_v1beta1_product.yaml, config/samples/capabilities_v1beta1_proxyconfigpromote.yaml, config/samples/kustomization.yaml, config/scorecard/patches/olm.config.yaml
Jira: https://issues.redhat.com/browse/THREESCALE-11009
Verfication:
- oc login to cluster
- `operator-sdk scorecard ./bundle` - the expectation is that all tests passed
Missing:
Commented out 2 tests for now:
olm-crds-have-resources-test - need to investigate how to resolve it
olm-spec-descriptors-test - need analysis based on https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md#olm-descriptor-reference
=> THREESCALE-11009 scorecard tests updated p1

doc/community-release-build.md
Jira: https://issues.redhat.com/browse/THREESCALE-10719
3scale-operator Community Release Process Doc
=> THREESCALE-10719  Community Release Procedure for 3scale Operator

doc/operator-application-capabilities.md, doc/tenant-reference.md
Jira: https://issues.redhat.com/browse/THREESCALE-11154
- Documentation update  
- related to https://issues.redhat.com/browse/THREESCALE-10525
* Optional parameters added to Tenant CR:
* fromEmail
* supportEmail
* financeSupportEmail
* siteAccessCode
=> THREESCALE-11154 doc update - new optional info params in tenant CR

apis/capabilities/v1beta1/backend_types.go, bundle/manifests/capabilities.3scale.net_backends.yaml, config/crd/bases/capabilities.3scale.net_backends.yaml, doc/backend-reference.md
JIRA: [THREESCALE-11183](https://issues.redhat.com/browse/THREESCALE-11183)
This PR allows users to create a Backend CR that uses the WSS protocol for the `privateBaseURL`. This was already allowed for Backends created through the 3scale portal.
2. Run the operator locally or via OLM using prebuilt image
```bash
BUNDLE_IMG=quay.io/ckyrillo/3scale-operator-bundles:threescale-11183 make bundle-run
```
3. Create a Namespace, dummy s3 Secret, and APIManager CR:
```bash
kind: Secret
apiVersion: v1
metadata:
data:
type: …
```
=> THREESCALE-11183 Add support for Backend CRs using wss protocol

bundle/manifests/3scale-operator.clusterserviceversion.yaml, config/manifests/bases/3scale-operator.clusterserviceversion.yaml
JIRA: [THREESCALE-11195](https://issues.redhat.com/browse/THREESCALE-11195)
Adding 4.16 as `maxOpenShiftVersion` to 3scale-operator 0.12.1 mas.
=> THREESCALE-11195 Add 4.16 as maxOpenShiftVersion to mas 0.12.1

controllers/apps/apimanager_controller.go, controllers/apps/apimanager_status_reconciler.go, pkg/helper/redis_database_version.go, pkg/helper/system_database_versions.go
=> THREESCALE-11208 mas sync

version/version.go
JIRA: [THREESCALE-11224](https://issues.redhat.com/browse/THREESCALE-11224)
Eye review and passing PROW checks
=> THREESCALE-11224 Fix operator patch version to match midstream

pkg/upgrade/migrate_deployment_config_2.15.go
JIRA: [THREESCALE-10949](https://issues.redhat.com/browse/THREESCALE-10949)
This PR fixes the DeploymentConfig to Deployment migration code to preserve the items in a DeploymentConfig's Volume. The exact path is `DeploymentConfig.Spec.Template.Spec.Volumes[i].ConfigMap.Items`.
1. Checkout the `3scale-2.15-stable` branch
2. Prepare for a local install:
```bash
make install
make download
kind: Secret
apiVersion: v1
metadata:
data:
type: Opaque
EOF
DOMAIN=$(oc get routes console -n openshift-console -o json | jq -r …
```
=> THREESCALE-10949 Preserve DC volumes' items

version/version.go
JIRA: [THREESCALE-11520](https://issues.redhat.com/browse/THREESCALE-11520)
Fixes version for `2.15.1`
Passing the PROW checks and an eye review should be sufficient verification.
=> THREESCALE-11520 Update threescaleRelease version for 2.15.1

pkg/helper/system_database_helper.go
JIRA: [THREESCALE-11504](https://issues.redhat.com/browse/THREESCALE-11504)
This PR removes the check for a root user when using an external MySQL for the system database.
2. Prepare for a local install:
```bash
make install
make download
kind: Secret
apiVersion: v1
metadata:
data:
type: Opaque
EOF
apiVersion: …
```
=> THREESCALE-11504 Support non-root user with external MySQL

Dockerfile, bundle/manifests/3scale-operator.clusterserviceversion.yaml, config/manager/manager.yaml, pkg/3scale/amp/component/images.go
Verifcation
Tests on PR pass is enough.
=> THREESCALE-11570 move base image to registry and remove docker hub images

version/version.go
Patch Release 2.15.2 - version update
=> Patch Release 2.15.2 - version update

doc/apimanager-reference.md, doc/operator-user-guide.md, pkg/3scale/amp/component/system.go, pkg/3scale/amp/operator/system_reconciler.go
https://issues.redhat.com/browse/THREESCALE-11502
Verification: 
Follow steps from: https://github.com/3scale/3scale-operator/pull/1047
=> THREESCALE-11502 update to zync disable

pkg/helper/helper.go, pkg/helper/redis_database_version.go, pkg/helper/redis_database_version_helper.go, pkg/helper/system_database_helper.go, pkg/helper/system_database_versions.go
=> THREESCALE-11297 Preflight TLS and ACL

pkg/helper/redis_database_version.go, pkg/helper/redis_database_version_helper.go, pkg/helper/redis_database_version_test.go
=> THREESCALE-11850 Preflight check fails on redis-sentinel (2.16)

bundle/manifests/3scale-operator.clusterserviceversion.yaml, config/manager/manager.yaml, pkg/helper/podHelper.go
=> THREESCALE-11868 remove remaining traces of internal DB(s)

.circleci/config.yml, doc/dependency_decisions.yml, go.mod, go.sum, licenses.xml, pkg/3scale/amp/cmd/root.go, pkg/3scale/amp/operator/system_reconciler.go, pkg/helper/runtime_object.go, test/crds/crd_validation_test.go
Mostly cosmetic, cleanup dependencies and update license.xml file
=> Cleanup dependencies

controllers/apps/apimanager_controller.go, pkg/3scale/amp/component/system.go, pkg/3scale/amp/operator/system_reconciler.go, pkg/3scale/amp/operator/system_reconciler_test.go, pkg/helper/job.go
Backport #1094  to 2.16 branch
=> THREESCALE-11805 refactor system-app migration jobs (2.16)

pkg/3scale/amp/component/zync.go
Use the same zync-queue image for both init container and container
=> Use the same zync-queue image for init container
